### ISSUE TITLE
About flask docs translations

### ISSUE THREAD

**Issue by liks79** [pallets/flask#1023]
#756

Hello @kennethreitz , We've created 'flask-docs-kr' project in readthedocs.org. 
(http://flask-docs-kr.readthedocs.org/ko/latest/)
We hope to enable 'flask.readthedocs.org/ko/latest' URL.

Please add our flask-docs-kr project to official flask readthedocs.org project. 
('Admin -> Translations -> Existing Translations')

Thanks.

**Comment by keyanp** [comment]
Who would be maintaining the translated docs? I think providing links to unofficial translations might be helpful, but making them 'official' just creates more work.

**Comment by jeffwidman** [comment]
I think all the maintainers are in agreement that it's awesome folks are translating the docs, but we can't commit to keeping them maintained, so we can't imply they're "official".

**Comment by kennethreitz** [comment]
Have you seen what the Requests projects does? Effectively:

- someone forks the repo, translates the docs
- the translated docs are uploaded to readthedocs
- a link is added to the sidebar of the requests documentation

It's pretty obvious that they are unofficial translations, by URL alone, and the quality of content. But people find them extremely helpful in their respective communities.

**Comment by nmilo** [comment]
Should this issue be closed?

**Comment by davidism** [comment]
I took it out of the milestone. GitHub's timeline entries for milestones and tags is just confusing.

**Comment by blueboar2** [comment]
I want to ask similar question about Russian translation. OK, you can't check translation because you don't have any russian developers, so you can't make it as official translation.
But then, what i (and other translators) can do? Can you give a link to that translation, and say, that this is unofficial? Can i search for russian developers on some other sites and ask them to check translation? What if i translate docs commit-by-commit, so you will always see, is it new or outdated? So, if i want to translate it "right-way", how can i do it?

**Comment by qria** [comment]
@liks79 Is the korean version of flask documentation still maintained? I am interested in contributing to it in terms of both contents and scripting(for building docs, etc.).
