### ISSUE TITLE
Dev server fails to terminate, becomes orphan

### ISSUE THREAD

**Issue by fvgs** [pallets/flask#1304]
Running OS X Yosemite.
I had the dev server running and was toggling the debug option. i.e. app.debug={True, False} in my entry-point file. I started running without debug and was surprised that the server was loading changes I made to my templates without having to restart the server. This is the reason I was toggling the option. Though, this is not the issue, since I later learned that that was the correct behavior.

In any case, I proceeded to then set debug to True and save the entry-point file. I may have restarted the server at this point, but either way things were still running regularly. However, trouble ensued when I then commented the line setting debug to True (thus leaving it set to the default False value) and saved. After this, I restarted the server, but was met with a traceback ending in:

```
...
File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
```

I restarted the server multiple times, before and after relaunching the Terminal app, and was met with this traceback each time. From this I suspected the server process was still running and had been orphaned. Using Activity Monitor, I found a python process running and terminated it. After that, when I tried running the dev server, I received a smaller (though similarly-ending) traceback. (not sure what to conclude from receiving a different traceback)

I didn't get to do much more testing after that. I came to GitHub to begin documenting the bug when my MacBook suddenly restarted. I can't say the restart is related to this issue. However, the restart was due to an OS X panic relating to OSXFuse. I've never had an OS X panic since updating to Yosemite, so I find a correlation to the dev server issue possible.

**Comment by rahulrrixe** [comment]
You are getting this because because the socket on which the flask app was running is still running in daemon mode. It generally happens when you uses <code> control + Z </code> to stop the flask server instead try using <code> control + C </code>.

To see the process id and kill it, type these commands in your Mac terminal
```bash
$ losf -i:PORT         #flask app PORT correspond to 5000
$ kill -9 pid
```

**Comment by DasIch** [comment]
There are two processes in debug mode. The actual server runs in the child. What happened is that you killed the parent, which leaves the child alive. The child continues to run and gets "adopted" by the init process (it doesn't turn into a zombie, that's something completely different). 

This is completely normal and expected behavior. =

**Comment by untitaker** [comment]
I strongly doubt that Flask is responsible for crashing your Mac, and am not entirely sure how you killed the server for a floating (!= zombie) process to occur. If you want to kill both of them, I've found that killing their process group works quite well.

**Comment by hexturtle** [comment]
Thanks for the responses to this issue. As has been pointed out, I absolutely misspoke when I said 'zombie'. I really meant to state that it became an orphan process.

I can accept that it is the expected behavior. However, it seems rather peculiar that this would be anything other than a design flaw. Based on @DasIch's response, it sounds like Flask made the mistake of terminating only the parent and allowing the child to become orphaned. At the very least this causes an inconvenience to the user by having to switch it a different port or otherwise kill the orphaned process manually.

**Comment by untitaker** [comment]
Reopening this because I tend to agree from a usability perspective, however, I am not sure if this is even fixable.

**Comment by trekkadmin** [comment]
@DasIch  Thank you for explaining this issue!  I was pulling my hair out trying to kill the process and could never resolve the issue.

**Comment by davidism** [comment]
Unfortunately, I can't follow your steps to reproduce this, there's too much narration and guessing. The first and last paragraphs don't even seem relevant? If anyone is still having this problem, please open a new issue with exact steps to reproduce

**Comment by dyspop** [comment]
I ran into this after a reboot on macOS Sierra. The steps above worked fine, though there was a typo in the original instructions, here it is corrected:

```
lsof -i:PORT
kill -9 PID
```

replace PORT and PID with their corresponding values.
