### ISSUE TITLE
Handling HTTP 405 on the blueprint level

### ISSUE THREAD

**Issue by jmagnusson** [pallets/flask#1494]
I really like being able to override the error templates for each blueprint using their errorhandler methods. All error codes work great for me. Except one. 405's are _AFAIK_ not catchable by the blueprint. This is a bit unfortunate when you have a JSON REST API where you want your consumers to be able to parse the data that they get back.

[This line in `werkzeug.routing`](https://github.com/mitsuhiko/werkzeug/blob/2b2d921eea7d1f896ce436ec5238890abe8b81bf/werkzeug/routing.py#L1558) is where the exception is raised. I feel a bit lost about the whole flow of a request in werkzeug/flask and don't really have any idea what I could do to be able to catch it in the Blueprint. Is this a bug? A known "feature"? Or am I doing something wrong?

Here's a test case which shows this behavior:

``` python
import unittest
from flask import Flask, Blueprint, request

app = Flask(__name__)
myblueprint = Blueprint('myblueprint', __name__)


@myblueprint.route('/', methods=['GET'])
def hello():
    return 'hello world!'

myblueprint.errorhandler(405)(lambda e: ('myblueprint 405', 405))
app.register_blueprint(myblueprint)
app.errorhandler(405)(lambda e: ('app 405', 405))


class BlueprintOrAppTestCase(unittest.TestCase):

    def setUp(self):
        self.client = app.test_client()

    def test_200(self):
        resp = self.client.get('/')
        self.assertEqual(resp.status_code, 200)

    def test_405(self):
        with app.test_client() as client:
            resp = client.post('/?http405')
            self.assertEqual(resp.status_code, 405)
            self.assertEqual(resp.get_data(True), 'myblueprint 405')
            self.assertEqual(request.blueprint, 'myblueprint')


if __name__ == '__main__':
    # app.run(use_reloader=True)
    unittest.main()
```

Running this gives:

``` python-traceback
.F
======================================================================
FAIL: test_405 (__main__.BlueprintOrAppTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 30, in test_405
    self.assertEqual(resp.get_data(True), 'myblueprint 405')
AssertionError: 'app 405' != 'myblueprint 405'
- app 405
+ myblueprint 405


----------------------------------------------------------------------
Ran 2 tests in 0.013s

FAILED (failures=1)
```

A version which tests more error codes can be found [in this gist](https://gist.github.com/jmagnusson/477d209ca3cee464674d).

**Comment by untitaker** [comment]
It certainly seems like a rough edge, similar to #1498

**Comment by jmagnusson** [comment]
Kind of, but at least there we know of [a workaround](https://github.com/mitsuhiko/flask/issues/1498#issuecomment-111709325).

**Comment by svieira** [comment]
@jmagnusson - the way to work around this (just like in #1498) is to compose distinct Flask *applications*, rather than trying to make a blueprint handle 405s.

@untitaker - I think one way to help people for whom this is an issue (for 1.x or 1.0 if that ship hasn't sailed yet) would be to add a new registration method to `flask.Flask` that does [app composition](http://flask.pocoo.org/docs/0.10/patterns/appdispatch/) from another app or a blueprint.  Something like `app.mount_app(bp_or_app, url_prefix=None, subdomain=None, **config_args)`  Doing something like this could also help with issues like #1507 as well.

**Comment by jmagnusson** [comment]
@svieira Interesting idea about using app composition. However, don't we miss out on features like linking between them with `url_for`?

**Comment by svieira** [comment]
You would need to add to the set of [`Flask.url_build_error_handlers`](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.url_build_error_handlers) so that the parent app (at least) could use `url_for` to route to the children.  You *could* also update the children so the children could route to the parents, but that's probably not a good idea in the general case (too much magic to avoid the infinite recursion problem + the children shouldn't be aware of the parents if they really are stand-alone applications that just happen to be mounted together for convenience)

**Comment by jmagnusson** [comment]
Sounds kinda messy. I kind of like the simplicity we have today where we just add Blueprints to our app to add more HTTP endpoints.

Couldn't there be some other way to make 405 catchable? An idea I have is that we make Flask create "fake routes" for each method in the [url_map](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.url_map). This would make it work a bit like [your workaround](https://github.com/mitsuhiko/flask/issues/1498#issuecomment-111709325) for 404s not being catched by the blueprints.

**Comment by svieira** [comment]
You're absolutely right, you *could* iterate over all the defined routes in a blueprint and add a route handler for the `url + (all_possible_http_methods - route_accepted_methods)`.  However, [as it currently stands][bp-url-reg] Flask does not make this easy.  The routes in a Blueprint [are stored as a closure that will just call `BlueprintSetupState.add_url_rule` when the Blueprint is registered on the application][bp-url-reg] ... and the `add_url_rule` method of `BlueprintSetupState` basically just forwards on its arguments to `Flask.add_url_rule`.

So you are left with either:

* Reflecting the nonlocals of the lambda function of each entry in [`Blueprint.deferred_functions`](https://github.com/mitsuhiko/flask/blob/595fb7e1fac3eea207816a700565f6a549e160d3/flask/blueprints.py#L103)
* Overriding `add_url_rule` and `register` for your Blueprint sub-class to store the extra meta-data and register the 405 method handlers.

  [bp-url-reg]: https://github.com/mitsuhiko/flask/blob/595fb7e1fac3eea207816a700565f6a549e160d3/flask/blueprints.py#L166-L173
