### ISSUE TITLE
Remove old version added and changed tags

### ISSUE THREAD

**Issue by davidism** [pallets/flask#1704]
Some of these lists are getting a bit long and irrelevant.  We should remove everything that wasn't added or changed in 1.0 for the 1.0 release.  This will reset the baseline that things will be added or changed from in the future.

**Comment by davidism** [comment]
Should at least leave 0.10 and 0.11 tags.  Should ensure that everything mentioned in the changelog has a tag in the docs.

**Comment by dawran6** [comment]
I'm working on it in PyCon

**Comment by untitaker** [comment]
I'm not sure what to do with those. Ideally they would be only hidden. We should look at what other projects do.

**Comment by dawran6** [comment]
What do you guys think about commenting out those version tags instead of hiding those?

**Comment by ThiefMaster** [comment]
IMO that just adds noise. Committing commented-out stuff is rarely a good idea

**Comment by untitaker** [comment]
@ThiefMaster @dawran6 I thought about this too. I think it's a reasonable approach, but I'd rather consider all options first. So here they are:

* removing
* commenting out
* Hiding old version markers automatically
    * via a Sphinx extension
    * via CSS

**Comment by jeffwidman** [comment]
My vote is to remove them because I don't think they're relevant to anyone reading the current version of the docs. Flask 0.9 was released nearly four years ago, so very unlikely to be used by anyone for new projects. 

Anyone who needs them for legacy projects can still dig them up by pulling up the old versions of the docs. There's been a number of changes in the docs since 0.9, so legacy projects will still need to pull up those old versions anyway.
