### ISSUE TITLE
Remove ext migration tool from source, link to separate package

### ISSUE THREAD

**Issue by davidism** [pallets/flask#1765]
This moved to its own repo: [pocoo/flask-ext-migrate](https://github.com/pocoo/flask-ext-migrate).  It should probably be removed from the Flask repo and the documentation should be updated to mention the migration tool.

**Comment by jeffwidman** [comment]
Is the `pocoo` github org staying around? 

It's mostly Flask stuff. Now that Flask sits under `pallets`, I wasn't sure if those repos will get moved around as well. Not saying they should all get moved to `pallets`. For example, `flask-ext-migrate` repo would probably be just fine under @keyan 's handle since he did much of the work and it's a convenient helper rather than a critical piece. Those decisions are above my paygrade though.

**Comment by keyan** [comment]
Yup this is reasonable.

**Comment by untitaker** [comment]
I've just moved flask-ext-migrate to the pallets organization and gave everybody in the Flask team access to it. I think this is a better solution, I'm very vary of creating single-user dependencies in the Flask ecosystem.

It's unlikely that it's going to change much or need maintenance, but we shouldn't take the risk.

**Comment by untitaker** [comment]
BTW @keyan if you *really* want to have the migration tool under your handle, or think you generally get too little credit for it, we definetly should figure something out though.

**Comment by keyan** [comment]
Thanks @untitaker, nothing like that at all. It doesn't make much difference to me either way. Fine with whatever is best for the project.

**Comment by jeffwidman** [comment]
> I've just moved flask-ext-migrate to the pallets organization and gave everybody in the Flask team access to it.

FYI @untitaker looks like you gave the Flask team read access, probably you want to change that to write access.

**Comment by untitaker** [comment]
Yes, sorry, fixed.
