### ISSUE TITLE
[RFC] template load performance, Blueprint.render_template

### ISSUE THREAD

**Issue by pedia** [pallets/flask#1792]
The loading of template tried too much times(count of blueprints), after setting with EXPLAIN_TEMPLATE_LOADING config. 

Maybe **Blueprint.render_template**  is more effective.
1.  In huge application, there are too much Blueprints, the performance is important.
2.  An independent  module should always use independent template and Blueprint. Just like below in a view.py

``` python
mod = Blueprint('standalone', __name__, url_prefix='/evil', \
  template_folder='standalone/templates', \
  static_folder='standalone/static')

@mod.route('/')
def index():
    # add a function into Blueprint
    return mod.render_template('index.html')
```

**Comment by untitaker** [comment]
@mitsuhiko Thoughts?

I personally would like to see a PoC and benchmarks that show any significant change in performance. I suspect that template loading is not an actual bottleneck.

**Comment by ThiefMaster** [comment]
I'd like to see a benchmark too.

But blueprint-local templates would be useful in any case. I'm currently using a slightly ugly hack (*) to have virtual folders for blueprints inside the merged template folders which means IDEs like PyCharm won't be able to link templates nicely since they don't know about it - with something builtin into Flask that'd probably change.

But even with blueprint-local templates it'd be important to keep the ability to access other templates (at least from the main app) from a blueprint template, e.g. to inherit from a base template or to include common macros - so using completely separate jinja environments most likely won't be an option.

---

(*) See the `virtual_template_folder` code in https://github.com/indico/indico/blob/master/indico/web/flask/wrappers.py#L173 for the hack I'm using.

**Comment by jeffwidman** [comment]
For reference, other issues discussing blueprint / template handling:
https://github.com/pallets/flask/issues/1361
https://github.com/pallets/flask/issues/266

**Comment by mitsuhiko** [comment]
Is the issue that template loading in general is slow or just when the debug feature is enabled? I'm not entirely sure I understand the bug report.
