### ISSUE TITLE
Slow json decoding for huge objects

### ISSUE THREAD

**Issue by rladeira** [pallets/flask#1793]
While doing some tests decoding some huge json objects, I am observing a very slow decoding behavior. Actually, it takes a lot of time to execute request.json the first time.

What's the default json decoder for flask? Does it use some C optimized code?

**Comment by davidism** [comment]
Flask uses the built-in `json` module, or `simplejson` if it is available.

**Comment by Machuntox** [comment]
Hi. I'm facing the same issue. We want to use [orjson](https://pypi.org/project/orjson/) instead of simplejson, but I don't know how to implement it and can't really find enough documentation about it. 

Could you provide more documentation or an example how to use [orjson](https://pypi.org/project/orjson/) instead of simplejson / json? It has something to do with "app.json_decoder = ", right?
