### ISSUE TITLE
Documentation for Flask + mod_wsgi + pyvenv + Python 3 doesn't work

### ISSUE THREAD

**Issue by cdman** [pallets/flask#1948]
It says [in the documentation](http://flask.pocoo.org/docs/0.11/deploying/mod_wsgi/) (the last section - "Working with Virtual Environments"):

> For Python 3 add the following lines to the top of your .wsgi file:
> 
> ```
> activate_this = '/path/to/env/bin/activate_this.py'
> with open(activate_this) as file_:
>     exec(file_.read(), dict(__file__=activate_this))
> ```

However `activate_this.py` is no longer present in pyvenv (see http://bugs.python.org/issue21496), thus the above code doesn't work. I found a stackoverflow answer where it said that just copying `activate_this.py` from a 2.7 virtualenv might work, however I didn't go down that route.

How I managed to get it working:

I added `WSGIPythonHome /path/to/env` to the top level of my apache config (ie. outside of VirtualEnv). However that might be a little to big of a hammer if people want to run multiple applications in the same Apache instance. In that case setting `python-path` on `WSGIDaemonProcess` might work (however I didn't try it out).

**Comment by Thynix** [comment]
`python-home` on `WSGIDaemonProcess` also exists, but as I'm having similar problems currently I can't speak to whether it works.

**Comment by Thynix** [comment]
`python-home` was added in `mod_wsgi` [version 3.4](https://modwsgi.readthedocs.io/en/latest/release-notes/version-3.4.html). I think it'd be reasonable (and once / if I get this weirdness sorted out I intend to open a pull request) to depend on this in the documentation because:

* 3.4 was released [in 2012](https://github.com/GrahamDumpleton/mod_wsgi/releases/tag/3.4)
* 3.5 was released [in 2014](https://github.com/GrahamDumpleton/mod_wsgi/releases/tag/3.5), contains a fix for a local privilege escalation vulnerability when using daemon mode, and the releases notes "[recommend] that prior versions of mod_wsgi not be used."
* Debian Jessie [ships 4.3.0](https://packages.debian.org/search?keywords=libapache2-mod-wsgi&searchon=names&suite=stable&section=all) as of this writing.

**Comment by simonli** [comment]
> `ddddddd`

**Comment by Ajiteshrock** [comment]
USE activate.bat

**Comment by djfurman** [comment]
Happy to take a stab at this if we can discuss preferred deployment strategies (things you want to support in your docs).

I'm not sure I'd directly embed mod_wsgi or mod_asgi with httpd/apache2 as my prod reverse proxy; NGINX should also be considered along with docker and running Flask with gunicorn or uvicorn to throw a possible approach out there.

The Flask app should be segregated into a non-privileged user at the *nix level and then use vevn to make sure it's not running in the system Python installation.

These are my initial thoughts/opinions only (I know there are lots of valid points and perspectives in this space) but I'm happy to lean in on this space.

**Comment by djfurman** [comment]
@davidism - volunteering for this one

**Comment by cdman** [comment]
Quick drive-by comment: the page we're talking about here is now at https://flask.palletsprojects.com/en/2.1.x/deploying/mod_wsgi/#working-with-virtual-environments

**Comment by davidism** [comment]
I'd like to replace this with how to use mod_wsgi-express instead, the modern recommended way to deploy with mod_wsgi.

**Comment by davidism** [comment]
Closed as part of #4637
