### ISSUE TITLE
Support same-site cookies

### ISSUE THREAD

**Issue by jootuom** [pallets/flask#2030]
There's a new RFC for preventing CSRF by restricting cookies to same-site only (i.e. no 3rd party cookies).
At least Chrome seems to support it since the developer tools list it if you look at cookies.

Adding support for it in Flask should be pretty simple. (Add an attribute to Set-Cookie when setting the session cookie and a configuration option to configure this.)

See:

https://tools.ietf.org/html/draft-west-first-party-cookies-07

**Comment by r0fls** [comment]
For the record, same-site does not restrict 3rd party cookies. It does prevent the browser from sending the cookie to other domains than the current site:

> Subsequent requests from that user agent can be expected to contain the following header field if and only if both the requested resource and the resource in the top-level browsing context match the cookie.

**Comment by r0fls** [comment]
Also this would probably make more sense as an issue with https://github.com/pallets/werkzeug

**Comment by r0fls** [comment]
For the record:
https://github.com/pallets/werkzeug/pull/1046

If that is merged it will make more sense to add support for it here.

**Comment by jab** [comment]
In https://www.chromium.org/Home/chromium-security/ssca the Chromium developers advise web applications to enable SameSite cookies whenever possible to mitigate Spectre.

> If that is merged it will make more sense to add support for it here.

Support for SameSite cookies landed in Werkzeug in https://github.com/pallets/werkzeug/pull/1167 and was released in Werkzeug 0.14.0.

https://github.com/pallets/flask/blob/master/docs/security.rst#set-cookie-options says SameSite cookies are not supported by Flask yet. It seems there is no longer an open issue to track adding this support. Make sense to reopen this issue to track this? It's useful to have an open issue that users can subscribe to who want to find out when support has landed. Maybe also change "same-site" to "SameSite" in the issue title since currently searching this repo for "samesite" doesn't turn up this issue.

/cc @davidism @mitsuhiko @untitaker @DasIch et al.

**Comment by davidism** [comment]
#2587

**Comment by jab** [comment]
@davidism It looks like #2587 is just for updating the docs, but doesn't Flask also need to add support for enabling SameSite for the session cookie via some `SESSION_COOKIE_SAMESITE` setting (à la `SESSION_COOKIE_HTTPONLY`)?

**Comment by davidism** [comment]
Oh, you want something specific to the session cookie. Updated.

**Comment by jab** [comment]
Thanks.
