### ISSUE TITLE
Problems with unicode

### ISSUE THREAD

**Issue by javixeneize** [pallets/flask#2099]
Hi

Looks like flask works different than plain python with Unicode. Let me explain

If i assign an unicode string to a parameter, (test="%$£") it works fine

When i run this code as part of a flask execution, i have an error. UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)

I can encode this in utf-8, but i would like to understand why the behaviour is different using flask?

Thanks

**Comment by ThiefMaster** [comment]
You forgot to include a traceback or a minimal script to reproduce the issue.

**Comment by javixeneize** [comment]
I am using python 2.7

Thats my code

@app.route('/test', methods=['POST'])
def test():   
    params='test'
    paramb=params.replace('st','%$£')


Thanks

**Comment by runfalk** [comment]
While your example does result in a UnicodeDecodeError, so does the same code without Flask:

```
from flask import Flask

app = Flask("test")

@app.route("/test")
def test():
    params = 'test'
    paramb = params.replace("st", "%$£")

app.run()
```

This results in UnicodeDecodeError on line 8 when run. The problem is the British pound sign which is not part of the ASCII character set. This error happens even before Python has loaded Flask. It can be fixed by adding ``# -*- coding: utf-8 -*-`` to the top of your file (as described in PEP 0263). If I reduce your code to a single line: ``"test".replace("st", "%$£")``, I still get the same error. 

Your working case is testing this in a REPL, I assume, which is why it works. This is because the REPL already knows the encoding of the input, which is by it works.

**Comment by javixeneize** [comment]
Hi

I have added this and still same error

    v = self._sslobj.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in
position 120
: ordinal not in range(128)
127.0.0.1 - - [25/Nov/2016 08:56:45] "POST /send HTTP/1.1" 500 -

**Comment by xiaocaiyidie** [comment]
mark, i get the same error

**Comment by javixeneize** [comment]
Hi. Any update on this?

I have tried python app directly from the console and it is displayed converted (['\xc2\xa3']), but flask is still failing 

Thanks

**Comment by davidism** [comment]
The one line of traceback you provided, `v = self._sslobj.write(data)`, is clearly not related to the code you say causes the error, `paramb = params.replace("st", "%$£")`.

I cannot reproduce your error in Python 2 or 3. The following code returns the expected response without error in both versions.

~~~python
# coding=utf-8
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
	return 'test'.replace('st', '%$£')

app.run()
~~~

Please use Stack Overflow for support with your own code. This tracker is for issues with Flask's code. Be sure to include a [Minimal, Complete, and Verifiable Example](http://stackoverflow.com/help/mcve) when asking, as well as in any future bug reports. Part of this would be the full traceback, as well as code that actually reproduces the problem.
