### ISSUE TITLE
Bind to IPv6 and IPv4 simultanously (Dual Stack operation)

### ISSUE THREAD

**Issue by TheDiveO** [pallets/flask#2239]
At this time, `Flask.run()` accepts only a `host=` parameter containing a single address. While `::` for the Linux kernel also accepts IPv4-mapped IPv6 addresses from the `::ffff:0.0.0.0/96` range, other dual stack implementations, such as Windows (and OpenBSD I think) do not map IPv4 addresses into the IPv6 address space for (IMHO sound) security rationales.

Please support binding to multiple addresses, thus supporting dual stack deployment, such as `host=('0.0.0.0', '::')`.

**Comment by ThiefMaster** [comment]
What's the point of this? The builtin server is just for development anyway.

**Comment by davidism** [comment]
This would be an issue with Werkzeug, not Flask. But yeah, don't really see why the dev server would need to bind multiple addresses.

**Comment by TheDiveO** [comment]
@davidism Okay, so I'm looking into Werkzeug. Binding to multiple addresses is necessary, because you need to bind to IPv4 ANY separately from IPv6 ANY. Do you have any IPv6 and Dual Stack experience?

**Comment by ThiefMaster** [comment]
Can you please explain why you need dual stack in a server that is **only** suitable for development? It **must not** be used in production.

**Comment by TheDiveO** [comment]
@ThiefMaster can you please explain why a dual stack server is for production only? You **must** be joking, right? FWIIW I'm using it in a simulation environment inside lightweight docker containers, but need many instances of them in separate subnets. And yes, I'm running dual stack for a reason.

**Comment by TheDiveO** [comment]
@ThiefMaster you are repeating yourself. But thank you for letting me know what kind of people are behind Flask. Help my colleagues to get a clear opinion. Thank you for telling me what I need to know.

**Comment by TheDiveO** [comment]
Gevent looks like an option to me, as I need to keep resources low in the comtainers, because I run many of them in parallel.

**Comment by ThiefMaster** [comment]
Not sure what your problem is, but no developer likes feature requests that don't seem useful or sound like someone did not understand the goal something (e.g. "flask's embedded server is meant for development only").

Either way, you are welcome to contribute dual-stack support, if it's a well-made PR I'm sure we'll appreciate it. However, AFAIK you cannot bind a single listening socket to both IPv4 and IPv6 unless you bind to all IPs (HAProxy has an option for this ("v4v6")). And while I'm not extremely familiar with the dev server's internals it might add lots of complexity to the code if it suddenly needs to deal with multiple listening sockets.

BTW: If all you need is a pure-python server, you can also have a look at cherrypy's webserver. It's quite easy to run Flask (or any other) WSGI app inside it.
