### ISSUE TITLE
Generating relative url with app context should not require SERVER_NAME

### ISSUE THREAD

**Issue by davidism** [pallets/flask#2255]
This is a pattern to generate the url to pass to the test client during testing, instead of writing out the url manually.

~~~python
with app.app_context():
    url = url_for('foo', _external=False)
~~~

This currently fails if no `SERVER_NAME` is set, even though it's not needed for relative urls. `url_for` could be modified to support the case where there's only an app context and `_external=False` was passed. Instead of raising an error, create an adapter with a dummy server name, like `localhost`.

Documenting the pattern in the testing docs might be useful too.

Continued from #801.

**Comment by davidism** [comment]
On the other hand, having the developer set `SERVER_NAME='localhost'` during testing doesn't seem unreasonable. @untitaker thoughts?

**Comment by untitaker** [comment]
Generating relative URLs shouldn't require a server name, but since not having a server name will probably break the app in other ways I see no reason to change it (especially as the patch for this -- creating a dummy server name internally -- isn't too pretty). As you say you can set the server name or use `test_request_context` when building the URL.
