### ISSUE TITLE
The example flaskr can't easily be run by a beginner in Flask framework

### ISSUE THREAD

**Issue by nuaalida** [pallets/flask#2437]
Even if I followed the instruction sequences in the README file in the project flaskr, I still couldn't correctly run this application. It's so depressing. I have already seen another similar issue #1902, but it is not helpful.

**Comment by wgwz** [comment]
So what is the error/s you are running into? You should try working through the tutorial (if you haven't already). It explains each step in detail. But I will look into this, it may be my fault that the readme is not in sync on flaskr.

**Comment by wgwz** [comment]
One problem I did run into on master is that the flaskr example is only working with master. This is bc of the fact that the readme specifies using the new `FLASK_APP` with an app factory pattern. That feature is not supported in the 0.12.2 release. So installing directly from `examples/flaskr/` does throw an error.

Aside from waiting for a new release, you could create an `wsgi.py` file or the like, in the flaskr example to instantiate the application. I suppose the best thing to do is mention both ways in the readme. 

Also a lesser issue I ran into is that this: `export FLASK_APP=flaskr.factory:create_app()`
Should be this: `export FLASK_APP="flaskr.factory:create_app()"`
Otherwise I get this: `syntax error near unexpected token `('`

**Comment by davidism** [comment]
Since this is master, we should add a .flaskenv file instead of exporting vars.

**Comment by wgwz** [comment]
@davidism what do you think should be done about the backwards compatibility in this case? Should we add a wsgi.py? And explain both methods?

**Comment by davidism** [comment]
I'd rather add a warning to the README:

> If you're following the tutorial from a specific version of the docs, be sure to check out the same tag in the repository, otherwise the tutorial may be different than the example.

**Comment by wingchingman** [comment]
I have the same problem, but I figure it out.
try this

```Python
git clone https://github.com/pallets/flask.git
cd flask/
pip install -e .
cd examples/flaskr/
pip install -e .
export FLASK_APP="flaskr.factory:create_app()"
flask initdb
flask run
```

what the README missing is

1. `pip install -e .` need to be done in flask and flaskr, two dirs
2. `export ` statement need double quote

**Comment by thomasoflight** [comment]
This is what I get when I attempt the second 'pip install -e . ' --> Command "python setup.py egg_info" failed with error code 1 in /Users/thomasoflight/LL_SOFT/PYTHON/FLASK_GIT/flask/examples/flaskr/

**Comment by MaxValue** [comment]
I just want to reinforce what @davidism said: you need to checkout the correct version of the example. Clone the repo, then do `git checkout 0.12.2` That is the most current version which is documented. If that should change in the future just look at the URL of the documentation what version is current and then checkout that version.

**Comment by jcrben** [comment]
Even with the versions matching, there's some subtle differences. https://github.com/pallets/flask/blob/f347d3c59e3304474ca85b17e24261f127b27282/examples/flaskr/flaskr/flaskr.py#L20 (from 0.12 branch) to: https://web.archive.org/web/20170705130806/http://flask.pocoo.org/docs/0.12/tutorial/setup/

In particular, this line does not appear in the example code:

`app.config.from_object(__name__) # load config from this file , flaskr.py`

Does this line make sense? In the context of this example, it doesn't seem like `__name__` points to an object. The source code has an example of using this function like `app.config.from_object('yourapplication.default_config')`
https://github.com/pallets/flask/blob/470112dd6e708a18eb4ec1daa10c4ea276620dbf/flask/config.py#L153

Since the tutorial isn't pulling in code, tested directly, perhaps the recent warning should also note that the there may be subtle differences.

**Comment by davidism** [comment]
Name is the string representation of the current module. It's loading config from the current file.

**Comment by jcrben** [comment]
But how is it referencing the config from this current file? That file doesn't appear to have a config object to load.

**Comment by davidism** [comment]
There are no specific config objects. Flask just looks at upper case variables on whatever object you pass it. Modules are objects.

**Comment by jcrben** [comment]
But in this case, the snippet and the example code show no upper case variables, so it's not clear why  you would run `app.config.from_object(__name__)` in this context (and I've never seen something like that in a flask app, altho I'm not super experienced with flask).

For this line to make sense, it should have a line preceding it defining an actual config with a comment explaining that flask will automagically use upper case variables in the passed in object as config variables.

**Comment by davidism** [comment]
This discussion is all moot, since I'm already rewriting the tutorial and examples.

**Comment by davidism** [comment]
continued in #2513
