### ISSUE TITLE
Flask complete demo app

### ISSUE THREAD

**Issue by systemaker** [pallets/flask#2480]
Hi all, 

https://github.com/systemaker

If it can help you in study and practices, I would like to share with you a complete flask demo app, easy professional examples of common web services we can get with this great micro-framework flask ; Featurng bootstrap themes, authentication and backoffice admin, Secured admin panel, pagination, resources CRUD, modular structure, REST json responses or Html renders, some utils like config files for Nginx and Gunicorn and much more. 

### Environment
* Python version: 2 and 3
* Flask version: 0.12
* Werkzeug version: 0.11.15

**Comment by ThiefMaster** [comment]
Cool, but i don't see how this belongs in the flask issue tracker.

**Comment by systemaker** [comment]
for people who are looking for some examples

**Comment by ThiefMaster** [comment]
Your code isn't even that good (`from dateutil import *` and lack of PEP8 formatting at the first things I noticed). So I don't think we want to advertise this as an example project on using Flask.

**Comment by systemaker** [comment]
No problem, it's just a tribute, it can help on working examples in some issues

**Comment by davidism** [comment]
Thank you for your interest. I'd ask that if you want to advertise your projects to not do it here without prior consent from the maintainers. The mailing list is open to all, however.

Without even getting into the code, critiques:

* Any modern Flask example should be using `setup.py` to install in development mode and set up requirements. `pip install -e .`
* This tries to be a one-size-fits-all example, which are usually way too complicated for beginners and way too opinionated for advanced uses, especially with Flask's focus on flexibility.
* Your requirements should be direct dependencies, not an exhaustive list. See pipenv if you want to lock requirements.
* Uses direct SQL for schema management rather than a migration library (Alembic).
* Uses Tornado as a server. Tornado itself recommends against using it for WSGI apps.
* Puts config in a location inside the package code, which is not recommended for packages installed in production. Use the instance folder.
