### ISSUE TITLE
AttributeError: 'module' object has no attribute 'app'

### ISSUE THREAD

**Issue by leninworld** [pallets/flask#2483]
I pulled the latest master branch and ran "python setup.py install". 
Then, I tried to load flask.app.test_client(), but it fails.
Please let me know how to overcome this. Thank you!

---------------------------
 MOOLE04mac1231:flask moole04$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import flaskr
>>> t= flaskr.app.test_client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'app'
>>>

**Comment by davidism** [comment]
Because you have to create an app in your own project. `flask.app` is a module in Flask that has the `Flask` object you use to do that.

**Comment by ThiefMaster** [comment]
I think he's trying to do something with `flaskr`

**Comment by leninworld** [comment]
I followed what is shown in link http://flask.pocoo.org/docs/0.12/testing/.
Pls see the line "self.app = flaskr.app.test_client()". So it is expected to work. Please let me know if I am wrong.

**Comment by davidism** [comment]
In your interpreter you need to use `from flaskr import flaskr`, like the test file does.

**Comment by leninworld** [comment]
This is what I get when I try.

>>> from flaskr import flaskr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name flaskr

**Comment by davidism** [comment]
You didn't install flaskr in editable mode then.

**Comment by paragjagdale** [comment]
I don't want to use the name 'flaskr', and want to use 'admin' for my app name instead. So I followed the tutorial from the start but with the name 'admin', but when I run pytest, I always get error:   ImportError: cannot import name 'admin' from 'admin' 

My test file has the line:

`from admin import admin`

I already ran 
`pip install -e .`

Here's the whole test test_admin.py (instead of test_flasrk.py):

`
import os
import tempfile

import pytest

from admin import admin


@pytest.fixture
def client():
    db_fd, admin.app.config['DATABASE'] = tempfile.mkstemp()
    admin.app.config['TESTING'] = True

    with admin.app.test_client() as client:
        with admin.app.app_context():
            admin.init_db()
        yield client

    os.close(db_fd)
    os.unlink(admin.app.config['DATABASE'])


def test_empty_db(client):
    """Start with a blank database."""

    rv = client.get('/')
    assert b'No entries here so far' in rv.data
`
