### ISSUE TITLE
add ssl_context option to `flask run`

### ISSUE THREAD

**Issue by jscn** [pallets/flask#2594]
### Expected Behaviour

I expect to be able to pass the `flask run` command any of the options which are valid for the `Flask.run()` method:

```sh
$ FLASK_APP=myapp/run.py FLASK_DEBUG=1 flask run --host=0.0.0.0 --ssl_context=adhoc
* Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Specifically, I want to pass `ssl_context=adhoc`, but it seems sensible to extend the command to accept all valid keyword arguments for `Flask.run()` / `werkzeug.serving.run_simple()`.

### Actual Behaviour
```
Error: no such option: --ssl_context
flask run --host=0.0.0.0 --ssl_context=adhoc exited with code 2
```

### Environment

* Python version: 3.5.2
* Flask version: 0.12.2
* Werkzeug version: 0.12.2

**Comment by davidism** [comment]
There are three behaviors:

- "adhoc" generates a new self-signed cert each time
- paths to a cert and key file
- an `SSLContext` object

I'm not sure how far to go with the last one. I can accept a string then call `werkzeug.import_string`, but that's more limited than how the CLI imports the Flask object itself. It wouldn't support callables and would dump a stack trace on errors instead of showing it in the interactive debugger.

Werkzeug has a `make_dev_cert` method to generate permanent files instead of the temporary ones with "adhoc". I'm wondering if I should expose this as a `flask make_local_cert` command.

**Comment by jscn** [comment]
I'm not particularly familiar with the internals of Flask, or the Flask way of doing things, so take this with a grain of salt. Personally I'd not cover the last case at all. It doesn't really feel to me like a good option for a CLI. I'd suggest the user write their own command or app instance that uses their custom `SSLContext` instead.

**Comment by ayrusme** [comment]
The paths to a cert file and key file seem to be logical, since that's the behavior in Flask.run(). We pass a SSLContext object with the load_cert_chain function to load the cert and key.

**Comment by davidism** [comment]
`app.run` "accepts" any of the forms because they're just passed on as arguments to the underlying function.

**Comment by jscn** [comment]
Thanks @davidism !
