### ISSUE TITLE
support for " url_for('api.book', book_id='${bookId}') "

### ISSUE THREAD

**Issue by fushall1104** [pallets/flask#2732]
Could you add a optional param to flask.url_for ?  :) 
when I call  `url_for('api.book', book_id="${bookId}")`, 
returned value will be  `'/api/book/%{bookId}' `,
instead of `'/api/book/%24%7BbookId%7D' `

> a snippet in index.html
```html
<script>
    let bookId = '123';
    let url = `{{ url_for('api.books', book_id='${bookId}') }}`
	axios.get(url)
	...
	...
</script>
```
> a blueprint
```python
api = Blueprint(xx,xx,xx, url_prefix='api')
@api.route('/book/<str: book_id>')
def books(book_id):
    xxxxxx
    xxxxxx
    return xxx
```

**Comment by ThiefMaster** [comment]
We don't have any plans to do that in Flask since client-side URL building is not within its scope.

But you can use https://github.com/indico/js-flask-urls instead to properly build URLs in JS. It's a package I wrote at work very recently and while it's quite new it's working fine.
Unfortunately we didn't write documentation yet (nobody likes to do that :p) but there's an example application in the repo showing how to use it to build URLs in JS.
