### ISSUE TITLE
Request files are left in memory

### ISSUE THREAD

**Issue by AggressivelyMeows** [pallets/flask#2763]
### Expected Behaviour
When the request is over, the incoming files and JSON should be removed from memory

### Actual Behavior
The files and other request data is left in memory with no apparent way to close the objects. i have tried using the python garbage collector but that fails to find the files and other related data.

The memory is silently used up until flask is killed by the host

### Environment

* Python version: 3.6
* Flask version: 1.0.2
* Werkzeug version: 2.10

**Comment by ThiefMaster** [comment]
Which WSGI container/server are you using?

**Comment by AggressivelyMeows** [comment]
Flasks inbuilt developer server

**Comment by ThiefMaster** [comment]
Not suitable for production, so I'm not sure how relevant this issue is.

Also, there's `PRESERVE_CONTEXT_ON_EXCEPTION` (enabled by default in debug mode) which stops a request context from being removed in case of an exception. That will of course leak memory whenever a request finishes with an exception.

**Comment by davidism** [comment]
How are you seeing that memory is still held. Please include an example that we can use to reproduce the issue.

**Comment by AggressivelyMeows** [comment]
The problem was solved by making sure the request files were saved and closed on my end. Seems that not all of the files I was using had closed.
