### ISSUE TITLE
cannot call app.run() from custom cli command

### ISSUE THREAD

**Issue by miguelgrinberg** [pallets/flask#2776]
### Expected Behavior

There are situations in which you may want to implement a custom application runner. Two examples that I can think of are running the application under the Werkzeug profiler, and starting the application in a background thread to perform integration tests against it.

In these situations, most people would want to create a custom CLI command that calls `app.run()` to start the application after applying any necessary changes, such as enabling profiling, etc.

Example `bug.py`:

```python
from flask import Flask

app = Flask(__name__)

@app.cli.command()
def custom_run():
    app.run()
```

What I expect with the above example is that running `flask custom_run` starts the development web server.

### Actual Behavior

```
(venv) $ FLASK_APP=bug.py flask custom_run
/home/miguel/bug.py:7: Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == "__main__" guard to silence this warning.
```

I think this warning should only appear when `app.run()` is called from the global scope of the main module. This can be determined from the number of frames in the call stack. The warning should be issued only if the call stack has two frames, but should not if there are more than two. Thoughts?

**Comment by ngxlua** [comment]
@davidism Why no one responds, I think this question is awesome

**Comment by miguelgrinberg** [comment]
FYI, I included a fix for this problem in #2781.

**Comment by proximadata** [comment]
Hello!
I encounter the same problem... when can we expect this fix to be released? Thanks!

**Comment by mlboy** [comment]
good

**Comment by Great-Li-Xin** [comment]
I'm facing an unusual phenomenon; When I tried running the test class independently, the `test_selenium` test went just fine. And When I tried `Flask test --coverage` I got the `app.run()` warning.
And this error comes with an unusual stack trace that directly leads to the `threading.py` which is an integrated python package. Besides, I'm pretty sure that there is no `app.run()` in my code.👇
```
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py:865: Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == "__main__" guard to silence this warning.
  self._target(*self._args, **self._kwargs)
```

**Comment by Great-Li-Xin** [comment]
Moreover, I found the failure even in the sample code. However, everything goes fine when running the `test_selenium` separately.

**Comment by sktzofrenic** [comment]
I've found a solution to this that works in my case. I needed to have a separate flask app as a click command which failed when upgrading to 1.0. 

In my situation, I created `autoapp.py` and `autoapp_proxy.py` and changed out the environment variable for `FLASK_APP=<app>` depending on which version I needed to run so that `flask run` would pull the correct app. 

I think I prefer the fix in your PR but wanted to throw this out there as an option that may work for some people's use case.

**Comment by FrostDescent** [comment]
However, I still can not understand what's your means. You said that this warning should only appear when app.run() is called from the global scope of the main module, but the app.run() is call from a function decorated by cli. Could you please tell me how to do more exhaustively？ Thank you very much.

**Comment by RgnDunes** [comment]
I think importing `click` and `with_appcontext` might solve the issue. You can create custom command and maybe then you can try app.run() as shown below.

`
@click.command(name='execute')
@with_appcontext
def execute():
    app.run()

app.cli.add_command(execute)
`

**Comment by uselessscat** [comment]
I have this case.

I want to run tests through `flask test`. So i made a cli command like:

```
@app.cli.command()
def test():
    import pytest

    return pytest.main(['project/tests'])
```

But i some test i need to connect to external api, so I want to mock an application this way ([full example](https://gist.github.com/eruvanos/f6f62edb368a20aaa880e12976620db8)):

```
from flask import Flask
from threading import Thread

class MockServer(Thread):
    def __init__(self, port=5000):
        super().__init__()

        self.app = Flask(__name__)
        
    def run(self):
        self.app.run(port=5999)
```

but if i want to run the tests using `flask test` the server would not be created and then the tests fails.

I don't know if i am missing something? I thought that if i run a server from another thread it would works, but it is not.

**Comment by davidism** [comment]
@useless Using the `flask` command to run `pytest` is not an intended use case?  Use the `pytest` command to run pytest, you're just making things complicated for no reason otherwise.

**Comment by kajol16** [comment]
Warning: Silently ignoring app.run() because the application is run from the flask command line executable.  Consider putting app.run() behind an if __name__ == "__main__" guard to silence this warning. I am getting this error, I dont know how to solve it, as I am new to flask

**Comment by davidism** [comment]
Do what the error message says and guard (or don't call at all) `app.run()`.

**Comment by davidism** [comment]
I think the most I want to do here is to move the `FLASK_RUN_FROM_CLI` var to only be set from the `flask run` command, and not by _any_ `flask` command. That way, a custom `run` command can decide to call `app.run()` successfully. However, that comes with the standard issue with `app.run()`, that calling it necessarily imports it, which means any errors during import will crash the command instead of being handled by the debugger and reloader.

**Comment by davidism** [comment]
Actually, I don't think it would be good to only set that from `flask run`. Presumably, an unguarded call shouldn't interrupt _any_ command, not only the `run` command. You wouldn't want a server accidentally starting when you called `flask shell` or `flask db upgrade`.

Disabling this check is a pretty uncommon requirement, it would only come up if you're writing a custom `run` command that works by calling `app.run`, as opposed to `make_server`, etc. I'd recommend against this anyway, as importing your `app` means that the server will crash on reload instead of drop to the debugger on import errors. If you really want to, I think it's reasonable to unset the env var in the command.

```python
def custom_run():
    del os.environ["FLASK_RUN_FROM_CLI"]
    app.run()
```

I'm doing some other work on the CLI, I might think of a more "official" way to turn off this check. For now the env var is fine, even though it's not really a public API. Just pay attention to our changelog if unsetting it is something your library depends on.
