### ISSUE TITLE
flask --version should output werkzeug version

### ISSUE THREAD

**Issue by jaapz** [pallets/flask#2824]
### Expected Behavior

Running `flask --version` should output Flask, Python and Werkzeug versions, as those are the versions asked in the issue template on github.

### Actual Behavior

`flask --version` only outputs Flask and Python versions (and GCC, for some reason?).

### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by emil45** [comment]
I do not think it's a good idea to show users the `werkzeug` version. 
Most of the regular users of Flask don't know nothing about any `werkzeug` package.
Why do not you also display the version of `Jinja2` ?

**Comment by jaapz** [comment]
Like I said in the issue, people need to provide the werkzeug version when they want to file an issue on github. I think adding that version in the `flask --version` command people can more easily obtain all versions they need to provide.

**Comment by RyanSquared** [comment]
Perhaps it would be best to specify something like `--version --verbose` to print out the versions of _all_ "secondary" dependencies (in that they're required directly by Flask)?

**Comment by adamfaliq42** [comment]
Werkzeug
Jinja
MarkupSafe
ItsDangerous
Click

**Comment by davidism** [comment]
I'm not sure where the discussion is, but I deliberately did not include all the dependencies when the option was added. Some of them are inconsequential, any project will have multiple other dependencies that contribute to issues which must be pared down first to create an MCVE, and there's already a handy command to get all versions: `pip list`.

Adding Werkzeug is fine since I ask for that in the issue template, and there's already a PR open for that.
