### ISSUE TITLE
request points to wrong object in debugger when threading is enabled

### ISSUE THREAD

**Issue by rkomorn** [pallets/flask#2836]
### Expected Behavior

Debugger should show the right request object.

```python
Paste a minimal example that causes the problem.from flask import Flask, request
app = Flask(__name__)

@app.route('/')
def hello_world():
    print(request)
    x = y
    return 'Hello, World!'

if __name__ == "__main__":
    app.run(debug=True)
```

### Actual Behavior

We're seeing some honestly kind of dumbfounding behavior that makes no sense to us. I'm not a novice when it comes to troubleshooting things, but this one really baffles me because I'm basically certain I'm not doing anything weird.

Debugger doesn't show the right "request" object often. See https://pasteboard.co/HqFNzwq.png for a screenshot of a case where the browser's URL bar shows the right thing, printing the request object shows the right thing in console logs, but using the debugger does not.

The request object is sometimes unbound, sometimes right, and seemingly often "off by 1" based on history.

So far, we can only seem to reproduce this on Linux, using Chrome and Firefox (edit: at first we thought it wasn't happening with Firefox but we found a repro with Firefox on Ubuntu 16.04 ). It doesn't seem to be happening from a Mac OS chrome client.

### Environment
* Python version: both 2.7 and 3.6 (in virtualenv-based environments)
* Flask version: 1.0.x and it seems 0.12 as well
* Werkzeug version: 0.14.1
* Linux version(s): Ubuntu 18.04 , Ubuntu 16.04
* Chrome: Chrome/65.0.3325.183

**Comment by scotchka** [comment]
I ran git bisect, and according to it, this is the first bad commit:
https://github.com/pallets/flask/commit/3738f7ff99661fa0319ebe2d8228ad8c479fb46a

**Comment by davidism** [comment]
I'd rather try to fix the debugger.

**Comment by davidism** [comment]
The debugger is actually good with multiple threads, it's Flask's `request` object that's not. When there's an error, a single context is preserved on the stack, but this can get out of sync with multiple threads.

**Comment by davidism** [comment]
I think this might require changing how the debugger works, and how Flask interacts with it.

The debugger works by storing each frame by id when an exception occurs in the Flask app. When a debug console request comes in, it references the id of the frame to execute in.

Flask stores the current request on a stack, then pops it at the end of the request. In debug mode, it will preserve one item on the stack so that it can be inspected. This works for the test client, but breaks down in threaded mode since the assumption that the next request is related to the first one is no longer valid.

Instead of the request context stack preserving the request, it seems like it would be more powerful if whatever needed to preserve a request preserved and restored it. The test client could track one request when using the `with client` block. The debugger could add a `save_frame` and `restore_frame` API that Flask could implement to store extra information along with each preserved frame.

**Comment by davidism** [comment]
Can't get rid of Flask's preserve context behavior completely, as it's the only way to keep a reference to the context around long enough for the debugger middleware to store it somewhere. So I think I only need to add hooks to Werkzeug's debugger, then implement them in Flask.
