### ISSUE TITLE
Use of dotenv causes flask cli to fail.

### ISSUE THREAD

**Issue by DanCardin** [pallets/flask#2860]
### Expected Behavior

* Install dotenv
** (In my case, dotenv is installed for reasons other than flask)
* put a `.env` file in a folder somewhere above the python package
** (In my case, a `.env` file is being used with docker-compose.yml in a containing folder)
* create a minimal flask app and run `flask` (it should just work)

### Actual Behavior

Your app wont work if run, and `flask` prints the following traceback.

```pytb
Traceback (most recent call last):
  File "./lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
ModuleNotFoundError: No module named 'manage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lib/python3.6/site-packages/flask/cli.py", line 529, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "./lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "./lib/python3.6/site-packages/flask/cli.py", line 246, in locate_app
    'Could not import "{name}".'.format(name=module_name)
flask.cli.NoAppException: Could not import "manage".
```

### Environment
* Flask version: 1.0

If I create a `.env` file at the top level of my python package/distribution (e.g. next to setup.py), the issue is solved.

To me, it appears that the problem is in `flask/cli.py`, line 617 on master.
```python
    if new_dir and os.getcwd() != new_dir:
        os.chdir(new_dir)
```
`new_dir` is the result of `dotenv.find_dotenv` which looks upwards in the folder hierarchy. The resultant directory is then outside the context of the project, and the `os.chdir` causes any attempted imports of local code to fail.

I would have submitted a PR removing that `os.chdir`, but I wasn't sure it would have been accepted. I assume its there to allow someone to run `flask` from inside a subfolder of their application, but the location of the `.env` file isn't necessarily indicative of that.

**Comment by davidism** [comment]
Install your application, as described in the tutorial, and you should no longer have to deal with pythonpath issues.

**Comment by DanCardin** [comment]
If that's the advice you give everyone, then what's the purpose of the `chdir`?

**Comment by davidism** [comment]
For the common case where people have a simple application layout (as opposed to nested somewhere under a larger project directory).

**Comment by davidism** [comment]
There's also ways to disable dotenv if you have it installed for some other reason that doesn't match how Flask cli works. Not sure if that's released yet.

**Comment by mildmojo** [comment]
I'd like to add an anecdote.

I spent two days struggling with this bug, since a [popular tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world#commentform) recommended `python-dotenv` and it's listed as an attractive [optional dependency](https://flask.palletsprojects.com/en/1.1.x/installation/?highlight=dotenv) in the official docs. 

In my case, my hello-world project wasn't nested within another project. I have a `.env` file in my home directory that I `source $HOME/.env` in my `.bashrc` so I can keep the latter unified across machines and checked into version control. My projects live in paths under my home directory.

Separately, I have a large work project that will start using `flask run` to launch a number of apps from subdirectories in a large monorepo, where there may be a `.env` file at the repo root. We'll need to account for this issue and either create setup.py files for `pip install -e .` or use `python -m flask run`.

Maybe it would be helpful if `flask run` displayed its working directory as part of startup, to help highlight when dotenv hauls it way outside your project path. Or display the CWD when this particular import error appears.

> Install your application, as described in the tutorial, and you should no longer have to deal with pythonpath issues.

If I'd been following the official tutorial, I wouldn't have known to skip to the _end_ of the tutorial to find [this advice](https://flask.palletsprojects.com/en/1.1.x/tutorial/install/):

> Make the Project Installable
> This is being introduced late in the tutorial, but in your future projects you should always start with this.
