### ISSUE TITLE
add option timeout for redirect

### ISSUE THREAD

**Issue by TechComet** [pallets/flask#2864]
Hi,

add option timeout for redirect

**Comment by ThiefMaster** [comment]
Why would we add that? `Refresh` headers to do a timed redirect are VERY rare nowadays - usually they are only used on shady download sites showing you a useless "Your download is starting in X seconds" message instead of just starting it straight away.

Also, you can create a response and add whatever header you want manually - I don't see any reason to add a shortcut for this particular header to Flask.
