### ISSUE TITLE
Document clearly why the flask executable is recommended over app.run()

### ISSUE THREAD

**Issue by asmaier** [pallets/flask#2880]
Citing from issue #1575:

> The biggest one is to somehow make it clear why the flask executable is recommended over app.run() for local development and to gently guide this through from the documentation. ( https://github.com/pallets/flask/issues/1575#issuecomment-146516535) 

Looking through http://flask.pocoo.org/docs/1.0/quickstart/ I cannot see any explanation in this regard. I also don't understand why the name of the app must be exported as environment variable and cannot simply be an argument to the flask command. Without an explanation that seems very cumbersome to me. And what is the recommendation on how to run a flask app not for local development?

**Comment by davidism** [comment]
It's the quickstart, which is not the place to justify the existence of things. See the docs about the CLI for a long list of all the things it can do.

The environment variable is required due to how things work internally. I don't find it cumbersome. The CLI docs document multiple ways to automate setting it. You're welcome to submit a PR to add it as a CLI option. See #2292 for a summary.

The final section in the quickstart you linked to refers you to the documentation on deploying.

**Comment by asmaier** [comment]
Ok, thank you for the pointers. So I understand using
```
if __name__ == '__main__':
    app.run()
```
is still a perfectly valid method for invoking a non automatic reloading application. Only if you need an automatic reloading application using the flask executable is the preferred method.

This documentation for why the flask executable is recommended over app.run can be found at 
 - http://flask.pocoo.org/docs/1.0/server/#server

In addition some other reasons are given at
- https://github.com/pallets/flask/issues/1575#issuecomment-147103623
- https://github.com/pallets/flask/issues/1575#issuecomment-147116830

The documentation of the CLI (including the non-trivial integration into the PyCharm IDE) can be found at
- http://flask.pocoo.org/docs/1.0/cli/

Hope that helps anyone who is coming from an older version of Flask and was left confused by the documentation as I was.
