### ISSUE TITLE
Blueprints and Extensions and SQLAlchemy

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/flask#289]
We do not encourage people to create more than one database connection and to connect to databases in arbitrary extensions. The obvious exception are extensions whose sole purpose is to connect to databases. Dependency resolving is done by the developer. Eg:

``` #!python
app = Flask(__name__)
db = SQLAlchemy(app)
something = SomethingElse(app, db)
```

The problem comes with blueprints. If SomethingElse wants to define models it has to do that at a local scope where it has the reference to the db. Assuming it provides blueprints, how does the blueprint's views and other code get to the models? The sad truth is that if you make up blueprints on the fly the views in that blueprint don't know how to reference it.

**Comment by davidism** [comment]
There are a few solutions I've seen, depending on the use case:

* Inject dependencies and explicitly generate the views.  I think this use is well covered by [class based views][1] already.  During `init_app`, the extension generates the models and passes them to `as_view`.  This is similar to what @jfinkels mentions, except it's the user injecting the model explicitly, rather than the extension.
* Provide abstract bases for the models, and expect the user to subclass them and use callbacks to set proxies.  Flask-Login does this with `UserMixin`, `login_manager.user_loader`, and `current_user`.  This is useful when 
* Set properties on the extension instance, then pull them from `current_app.extensions['my_ext'].MyModel` in views.  I don't have an example off the top of my head, but this is a similar concept to Flask-Login's `login_manager.anonymous_user`.

I'll work on some short examples for each of these solutions to add to the docs on extensions.

**Comment by kennethreitz** [comment]
Closing as this issue is OLD.

**Comment by kennethreitz** [comment]
keeping open as this seems important

**Comment by MajidHeydari** [comment]
Does Flask-SQLAlchemy support Dgraph

**Comment by shreyam181** [comment]
can I work on it
