### ISSUE TITLE
Pin versions to avoid major updates of dependencies

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/flask#2954]
Currently we set minimum versions only, with no maximum version requirement. Should we prevent implicit updates to new major versions of any of our dependencies?

**Comment by davidism** [comment]
If we put upper limits in place, it means that even if the newer version doesn't cause any issues, or at least any issues relevant to a project, that project still can't upgrade. Pip allows but keeps warning about version mismatches if you force version upgrades.

This could be solved by making  releases that just re-pin dependency versions. But then we're in the same situation, there will be plenty of projects that weren't pinned and will have the same issue.

What is the version bump for a pin update? Major? It caused breaking changes (in this case, for specific use cases), but we're not going to release Flask 2.0 for It's Dangerous 1.0. Minor? Maybe, but that brings in the baggage of making a significant release, when we might not be ready for that. Patch? Then exact versions would have to be pinned, since `~` would upgrade to those automatically still.

**Comment by ThiefMaster** [comment]
I wonder what kind of pinning people use for Flask... Personally I pin exact versions for everything and do a manual update from time to time (after checking changelogs in case of non-patch version bumps, especially if the major version changed).

So my gut feeling would be to do a minor release to bump version pins.
