### ISSUE TITLE
server banner seems works not as expected

### ISSUE THREAD

**Issue by lt94** [pallets/flask#3014]
### Expected Behavior
I had already config the variable "ENV" in the config, which was set as 'development', It seemed that the banner should display "Environment: development",actually,it didn't. What's more, it worked with env development.

```python
# config
class Config:
    # ...
    @staticmethod
    def init_app(app):
        pass
class DevelopmentConfig(Config):
    ENV='development'

def create_app(config_name):
    app = Flask(__name__, static_folder='static', static_url_path='')

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    # ...
    print("*Actual Environment: {}".format(app.config['ENV']))
    return app

# wsgi.py
from app import create_app

application = create_app('default')
```

### Actual Behavior
```pyrb
 * Serving Flask app "wsgi.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
*Actual Environment:development
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
### Environment

* Python version: 3.6.5
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

**Comment by garenchan** [comment]
As the doc said, setting up the environment in your code may not work. You need to set it in the environment variables.
https://github.com/pallets/flask/blob/d5665e4ba6cf4f7eabdc0be047952a27965a455f/flask/app.py#L810-L814

On Windows:
```bat
set FLASK_ENV=development
```
On Linux:
```shell
export FLASK_ENV=development
```

**Comment by lt94** [comment]
@garenchan is it a bug? it worked actually, but just the banner display wrong

**Comment by davidism** [comment]
You've confused variables in Python code with environment variables. FLASK_ENV must be set as an environment variable. See the docs on the CLI for more information.

**Comment by garenchan** [comment]
@lt94 , it's not a bug. You should use `app.env` to get the actual environment.

**Comment by lt94** [comment]
thanks~

**Comment by davidism** [comment]
You cannot set the env with `app.env`. You must set it with the `FLASK_ENV` environment variable.

**Comment by garenchan** [comment]
@lt94 , I'm so sorry I misled you. You're right and this is indeed a bug.

- If you run your app with `flask` CLI, the `Environment` in the banner may be wrong. Because `flask` CLI may use a lazy loading strategy, it means that when you run `flask run`, the app may not be available yet, so `flask` cli can't know what the final `Env` is at this moment.  If you change the `Env` in the `create_app`,  then the `Environment` that was printed before will be wrong.
- If you run your app with `app.run`, you won't have this problem.

I can give a PR to solve this problem, but I think it may not be accepted. So my advice to you is to use `FLASK_ENV` environment variable to set the `Env`.
