### ISSUE TITLE
FlaskGroup does not work when nested in a click.group

### ISSUE THREAD

**Issue by gustapia06** [pallets/flask#3263]
### Expected Behavior
When using Flask CLI, I came to the case that we have a group of commands for a big program that uses `click`.
```python
# main group
@click.group()
@click.pass_context
def my_big_cli_group(ctx):
    pass

# sub group
@my_big_cli_group.group()
@click.pass_context
def my_nested_group(ctx):
    pass

# command for sub group
@my_nested_group.command()
@click.pass_context
@click.option('-s', '--start', is_flag=True)
def my_command(ctx, start):
    click.echo(start)
```

The issue comes when nesting my flask app into the bigger group using `cls=FlaskGroup` and passing my `create_app` factory function.

```python
# flask app sub group
@my_big_cli_group.group(cls=FlaskGroup, create_app=create_app)
@click.pass_context
def my_flask_app(ctx):
    pass
```

After running my `setup.py` pointing my entry point to `'my_big_cli = path.to:my_big_cli_group'`, I should expect the app to start once I do:
```bash
$ my_big_cli my_flask_app run
```

### Actual Behavior
Instead, I get a `flask.cli.NoAppException`. It seems that `create_app` does not get passed on to `Group.group` instances on `click`.

```pytb
Traceback (most recent call last):
 File “/Users/the_user/Desktop/venv/lib/python3.7/site-packages/flask/cli.py”, line 540, in list_commands
   rv.update(info.load_app().cli.list_commands(ctx))
 File “/Users/the_user/Desktop/venv/lib/python3.7/site-packages/flask/cli.py”, line 393, in load_app
   ‘Could not locate a Flask application. You did not provide ’
flask.cli.NoAppException: Could not locate a Flask application. You did not provide the “FLASK_APP” environment variable, and a “wsgi.py” or “app.py” module was not found in the current directory.
```

### Work around
If I don't nest the flask app into a group but rather make it a new `click.group`, then after changing my `setup.py` to point to this new entry point as well, everything works as expected.

```python
# flask app group
@click.group(cls=FlaskGroup, create_app=create_app)
@click.pass_context
def my_flask_app(ctx):
    pass
```
Then
```bash
$ my_flask_app run
```
works perfectly fine

### Environment

* Python version: 3.7.3
* Flask version: 1.0.3
* Werkzeug version: 0.15.4

**Comment by frostming** [comment]
There are some bootstrap code in `FlaskGroup.main()`, so I think it is not allowed to nest it in another group, because the function is never called.

**Comment by gustapia06** [comment]
Ah, interesting. Could there be any workaround for this to be allowed? I guess at the end `Flask` should be fully compatible with all `click` functionalities (group `nesting` being one of the main ones).

**Comment by frostming** [comment]
Passing create_app as a parameter doesn't work in this case, but you can still use FLASK_APP environment variable to do the trick. Note that some functionalities are still missing, such as dotenv loading.

**Comment by u8sand** [comment]
I also came across this issue, I dug into the source and was able to make a minor change which *seems* to do the trick. I have yet to test it more thoroughly however, perhaps someone here can figure out if this affects something else.

Quite simply I re-write FlaskGroup and replace `main` with `make_context` (naturally, the call and the `super()`) here https://github.com/pallets/flask/blob/master/src/flask/cli.py#L578-L597

This is because in click, one of the first things that are done in `main` is to call `make_context` with `kwargs` (https://github.com/pallets/click/blob/master/src/click/core.py#L809)

Which ends up here: https://github.com/pallets/click/blob/35f73b8c2c314e56968de8bc483da9a84ac5c53e/src/click/core.py#L712 
It looks to me like injecting kwargs into this function instead of main should work just as well. In my simple tests, this seems to enable me to run the flask apps using the new FlaskGroup in sub groups.

**Comment by aprilahijriyan** [comment]
Hi, I have a similar problem here https://stackoverflow.com/questions/64396186/how-to-manage-multiple-cli-flask-applications
