### ISSUE TITLE
RequestContext documentation

### ISSUE THREAD

**Issue by Lyla-Fischer** [pallets/flask#3311]
### Expected Behavior
I think that the documentation for mocking request contexts in Flask 1.1.x might be a bit off. I'm filing an issue instead of submitting a pull request in case there is something about my configuration that doesn't fit the target audience of the documentation. 

The docs say that in order to mock a request context, you should use the `with` functionality as such: 

```python
with app.test_request_context(
        '/make_report/2017', data={'format': 'short'}):
    generate_report()
```

### Actual Behavior
In order to actually gain access to the request context, I has to insert as `as` with the `with`
```python
with app.test_request_context(
        '/make_report/2017', data={'format': 'short'}) as request:
    generate_report(request)
```

It's not hard to guess, but it seemed like it might be worth updating the docs. 

### Environment

* Python version: 3.7.3
* Flask version: 1.1.1
* Werkzeug version:  0.15.5

**Comment by davidism** [comment]
The `request` object is essentially a thread-local, so it's typically used as an import instead of being passed as an attribute. `test_request_context` returns the request *context*, which is the thing that controls what `request` points at, not `request` itself, so your change isn't doing exactly what you meant.

So you'd typically define `generate_report` like:

```python
from flask import request

def generate_report():
    content_type = request.content_type
    ...
```

of if you want to be able to pass other request objects, use a default:

```python
from flask import request

def generate_report(request=request):
    ...
```

You'd need to use `ctx.request` if you used the `with/as` statement, but I don't think this is something I want to document as it's getting more internal.

```python
with app.test_request_context() as ctx:
    generate_report(ctx.request)  # flask.request points to the same thing though
```

**Comment by Lyla-Fischer** [comment]
Ah. I guess I was confused about how thread-locals work, and that you need `from flask import request` in order to access the variable `request` (I was just treating the availability of the variable as "magic I don't understand, but I can work with it anyway"). Thanks for the clarification.

**Comment by davidism** [comment]
If you have a specific change you think would make the docs clearer, I'm open to a PR, but going to close this for now.
