### ISSUE TITLE
Route Decorator redirects improperly

### ISSUE THREAD

**Issue by IceBearZero** [pallets/flask#3345]
### Expected Behavior
Using the route decorator (below), I expect going to `/devices/1` to execute the related method, but instead it throws a 308 redirect response back to `devices`.

If I change the url to `/devices/2` it properly executes the method

Removing the 3rd route decorator does not change the behaviour, `devices/1` still redirects

```python

@app.route('/devices', methods=['GET'], defaults={"page":1,"per_page":1})
@app.route('/devices/<int:page>', methods=['GET'], defaults={"per_page":1})
@app.route('/devices/<int:page>/<int:per_page>', methods=['GET'])
def devices_get(page, per_page):

```

```
devices_get           GET      /devices/<int:page>/<int:per_page>
devices_get           GET      /devices/<int:page>
devices_get           GET      /devices
```

### Environment

* Python version: 3.7
* Flask version: '1.1.1'
* werkzeug-0.15.5

**Comment by mdbottino** [comment]
Actually I think it's expected because of the way you set the routes. If you remove the `/devices` route it should work (exactly as before) but without redirects. 

Also, as a side note it would be cleaner if you put the defaults in the function definition instead of the route if they are all the same. The default method is GET if you don't specify otherwise. This would be equivalent but without redirects:

`
@app.route('/devices/<int:page>/<int:per_page>')
@app.route('/devices/<int:page>')
def devices_get(page=1, per_page=1):
`

**Comment by davidism** [comment]
This is expected. When multiple routes are associated with an endpoint and the route can be simplified by omitting defaults, Werkzeug's router (and therefore Flask) does so.

You'd notice the same thing if you went to `/devices/2/1`, it would redirect to `/devices/2` because the default for `per_page` is 1.

**Comment by IceBearZero** [comment]
Thanks everyone .. I tested this more and realized it was expected, and starts to make sense .. 
I also tried the defaults in the function def. and for reasons it didnt work, but I may have had too many moving pieces and was doing something dumb. Thanks

**Comment by IceBearZero** [comment]
Leaving this here as well, as mentioned, moving defaults to the method-def. works, and also removes the redirect, so things work as (I) expected ;) .. thanks again
