### ISSUE TITLE
Flask generates loggers that may collide with package name hierarchy

### ISSUE THREAD

**Issue by jjnurminen** [pallets/flask#3359]
Hi,

I have a Python package, let's call it `mypackage`. After creating a Flask app inside the package, I noticed that all logging messages from my own package started appearing twice.

I tracked the cause to Flask automatically creating a `logging.Logger` instance (accessible as `app.logger`) that has the name `mypackage`. This follows from the fact that name of my Flask app is also `mypackage` (this is required to set up some static assets correctly). However, as `logging.Logger` instances are singletons, Flask ends up accessing an existing logger inside my package hierarchy and silently attaching its own stderr handler to it. Since all logging messages from my package end up propagating into the `mypackage` logger (before they propagate to the root logger), I now get all log messages twice.

Possible remedies that I can think

- do not automatically set up logging handlers inside Flask, or only set them up in special circumstances
- if the app logger really needs to be automagically set up and equipped with a handler, give it a name of 'Flask.{insert_appname}' or something to reduce chance of name collisions

Using Flask 1.1.1, Python 2.7.16

**Comment by davidism** [comment]
Flask only attaches a handler if none are availablr already. Configure logging before accessing `app.logger` to avoid that.

I'm not changing this again. I can't make everyone happy, and the behavior has been this way forever. Override `Flask.logger()` if you need other behavior.

**Comment by jjnurminen** [comment]
>Flask only attaches a handler if none are availablr already. Configure logging before accessing >app.logger to avoid that

@davidism  I never accessed `app.logger`, it got accessed due to the name collision. I think changing the logger name, as suggested above, would be an easy way to avoid Flask loggers being confused with existing loggers.

**Comment by davidism** [comment]
Then something else is going on in your code. Flask only configures the logger when it's accessed through that proprety and is not already configured.

**Comment by jjnurminen** [comment]
@davidism Regardless of the configuration issue, I think Flask will rather easily end up using an existing logger due to a name collision (as the logging module provides loggers as singletons). IMO this is not desirable and could be easily avoided by naming the logger differently.

The logger getting configured automatically is another issue. I'm 100% sure my code is not touching `app.logger` (I was not even aware of it before I started debugging). However I'm using Flask via the Dash library, which may be doing something with `app.logger`.

**Comment by davidism** [comment]
That it shares the name with your project is intentional. Your app *is* your project. It is explicitly bound to the package name by `Flask(__name__)`. `app.logger` is used to log things you're doing from your app. If we were to log things about Flask's internals, then we'd use the `flask.app` name.

If your messages are appearing twice, it's because you configured your own handler *after* touching `app.logger`. Regardless of if you're using Flask, it is always good practice to configure logging as early as possible. Move your logging configuration to earlier in your startup process. If it's Dash that's doing this, and it's not fixed by moving the configuration earlier, then take it up with Dash.

Or if you want to change the behavior more thoroughly, override the `Flask.logger()` property with your own implementation, such as returning a logger with your preferred name.

```python
import logging

from flask import Flask
from flask.helpers import locked_cached_property

class MyFlask(Flask):
    @locked_cached_property
    def logger():
        return logging.getLogger("myproject.myapp")

app = MyFlask(__name__)
```

I already tried changing this to `flask.app`, and received valid issues asking to change it back. `flask.{name}` is confusing as it looks like messages logged from your project code are actually part of Flask's code. I do not plan to change the behavior of `app.logger` again at this point, at least as described by this issue.

**Comment by jjnurminen** [comment]
Thanks for your trouble @davidism . I understand the point about naming the logger.

FWIW, it turned out to be Dash that forcibly installs a logging handler. I'll take the issue up with them.
