### ISSUE TITLE
Features Request: Remove Python 2 support and add Async

### ISSUE THREAD

**Issue by timkofu** [pallets/flask#3363]
The first one is to fully leverage Py3 features. Also, Py2 EOL is due in a few months.
The second one is to add speed. Much speed. So Flask can handle more requests with the same hardware, and run smoother while doing so.

Maybe both of these are already in the works?

**Comment by ThiefMaster** [comment]
I think we can close this in favor of pallets/werkzeug#1322, as async features would not make much sense in Flask without having proper async support in Werkzeug.

> The second one is to add speed. Much speed. So Flask can handle more requests with the same hardware, and run smoother while doing so.

Non-async apps are not necessarily slower.



And while I think that dropping Python 2 at some point makes sense, this should not be before the Python 2 EOL - and if there are no issues supporting both I personally would even wait a bit longer with removing Python 2 support, since there WILL be many bigger applications that need some more time to be adapted to Python 3 (and many linux distros still support Python 2 for a while).

**Comment by davidism** [comment]
Regardless of when we drop Python 2 support, we don't proactively modify code to use newer patterns in most cases. Nothing in particular would change about Flask's code by dropping Python 2.

"asyncio is faster than traditional workers" is a falacy, the phrase is "asyncio enables a different paradigm to program in, but does not inherently make complex applications faster". We do plan to support ASGI (pallets/werkzeug#1322), but don't expect that to make your application faster. This is true for any application, not just Flask.

**Comment by techouse** [comment]
@timkofu Check out [Quart](https://pgjones.gitlab.io/quart/) if you want an Asyncio version of Flask.

**Comment by timkofu** [comment]
@techouse Thanks.

**Comment by AlliedToasters** [comment]
We migrated our flask endpoints to [fastAPI](https://github.com/tiangolo/fastapi) pretty smoothly, worth checking out in addition to Quart.
