### ISSUE TITLE
set cache-control: private when session is used

### ISSUE THREAD

**Issue by nottrobin** [pallets/flask#3423]
If ever the `flask.session` is used, and there's an intermediary cache between the Flask app and the user (Squid, Cloudinary, whatever), there's a significant risk that a user could see a page that was built for another user, exposing sensitive information (e.g. see https://stackoverflow.com/questions/13768007/browser-caching-issues-in-flask and https://github.com/mattupstate/flask-security/issues/334).

The solution to this is for the application developer to return a `cache-control: no-cache` or `cache-control: private` header with any pages that might contain sensitive information.

However, many project developers will likely forget to do this. Would it make sense for Flask to explicitly return a `cache-control: private` header by default if the `flask.session` is not empty?

In the meantime, we're planning to implement something like this in our apps:

``` python3
@app.after_request
def make_sessions_private(response):
    if flask.session:
        response.cache_control.private = True
        response.cache_control.public = False
    return response
```

Does this make sense?

**Comment by debendraoli** [comment]
Isn't it should be on `Flask-Session` extension?

**Comment by davidism** [comment]
The default session implementation already adds the `Vary: Cookie` header if the session was accessed. This instructs a cache to hold separate versions per user. I'm wary of adding `Cache-Control: private` because it seems too heavy, it tells a cache never to cache anything even though the problem you probably care about is not mixing up separate users.

I think it's probably better to use your `after_request` function to do `if session.accessed` if you need more strict cache control. Thoughts?

**Comment by nottrobin** [comment]
Oh I didn't realise that. I can see the `Vary: Cookie` header probably makes more sense as a default implementation, and should be sufficient to protect user's data. I think `Vary: cookie` is a very sensible default. Thanks for explaining it.

We did have a case where we were using Flask and we saw leaking of cached sessions between users, but maybe there was another cause that we missed.

Yeah you're right, we should probably be using `session.accessed`.
