### ISSUE TITLE
FLASK_APP does not work with bound methods

### ISSUE THREAD

**Issue by delwaterman** [pallets/flask#3538]
### Expected Behavior
Flask is unable to use bound methods when using the `FLASK_APP` environment variable with a module attribute listing

```python
# service.py
import Flask

class AppService:
    def __init__(self):
        pass
    def create_flask_app(self):
        return Flask("demo-app")

service = AppService()
MY_SERVER = service.create_flask_app
```

```console
$ FLASK_APP="service.py:MY_SERVER" flask run
```

Application should boot

### Actual Behavior
An exception is thrown:
```
flask.cli.NoAppException: A valid Flask application was not obtained from "service:MY_SERVER".
```

Issue is here: https://github.com/pallets/flask/blob/master/src/flask/cli.py#L171

`inspect.isfunction` returns false for a bound method.

### Environment

* Python version: 3.6.10
* Flask version: 1.1.1
* Werkzeug version:

**Comment by davidism** [comment]
This is really not how Flask or the CLI is expected to be used. Just create a function that calls that method if you really want to set things up this way.

**Comment by delwaterman** [comment]
I am sorry I am really confused by your comment. If the flask run command is able to use a function to start an application why not a bound method. Calling it would be identical. The only thing to change here would be to use two checks instead of one:

```python
 if inspect.isfunction(attr) or inspect.ismethod(attr)
```

I do have a workaround in place, but it feels rather hacky. 

```python
# See https://github.com/pallets/flask/issues/3538
    def app_factory(self) -> Callable:
        def _app_factory() -> Flask:
            return self.create_inference_engine_server()

        return _app_factory
```

Is there a difference between a function and a method that I am not understanding?

**Comment by davidism** [comment]
> If the flask run command is able to use a function to start an application why not a bound method.

The purpose of using an app factory is that you avoid global objects and can create multiple apps with different config. But by tying it to an instance method, you basically undo all that.

There's no point in having the class you've shown if you're going to create a single global instance of it in order to call its app factory. Since the CLI doesn't do attribute access (`myapp:service.create_app` wouldn't work), even if we support methods you still have to do what you've already shown to get access to the factory callable. With those two points, you may as well also add `app = service.create_app()` right after.

You can write a standard factory instead of your factory factory.

```python
service = AppService()

def create_app():
    return service.create_flask_app()
```

---

Ultimately, since I'm not really seeing the value of the class, I'm not willing to open up the use case of calling instance methods, despite it being a small amount of code. That's not to say you can't use that pattern, just that Flask's CLI won't help you as much as if you were using the common patterns.

**Comment by delwaterman** [comment]
I am writing a Pip package for my team to build custom Predictive models using a framework. My package is ultimately intended for Data Scientists that don't have context nor should be required to learn the context of the Webserver actually serving their prediction.

They want to focus on writing the function that makes the prediction, not on the implementation details of the webserver. So we have them install a pip package that includes Flask as a dependency.

With the current implementation I have to force my users to put ceremony code like:
```python
service = AppService(prediction_fn)
def app_factory():
    return service.create_flask_app()

APP_FACTORY = app_factory
```
This exposes the underlying webserver details to the user and clogs up their code. As opposed to my ideal code:

```python
SERVICE = AppService(prediction_fn)
```
This code allows me to properly mask not only a web server, but a number of other services that are implemented. I can structure various docker containers to reference environment variables defined by my users to start the correct webserver, etc.

I don't think I quite understand your motivation around eliminating global objects. Methods are inherently global objects. In addition, just because a method is an instance object doesn't mean that the object it will return will be the same. Our factory will probably return differently configured applications depending on environment variables, and will start different servers (flask vs gunicorn) for different environments.
