### ISSUE TITLE
use pathlib internally

### ISSUE THREAD

**Issue by mcshlain** [pallets/flask#3557]
### Expected Behavior
For the server to start correctly, this code used to work before 1.1.2. 
```python
from pathlib import Path

ui_dist_dir = Path(__file__).parent / "ui" / "public"
app = Flask(__name__, static_folder=ui_dist_dir, static_url_path="/static", template_folder=ui_dist_dir)
```

I'm not sure if it was intended to be used with `pathlib` before but since python2 support is being dropped I think it would make a lot of sense to support. I would even say that instead of manually replacing slashes in strings, it would be a good idea to use pathlib internally and not duplicate that logic in Flask.  

### Actual Behavior

```python
Traceback (most recent call last):
  File "/opt/spike/server/envs/default/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/spike/server/envs/default/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/spike/server/spike/start.py", line 140, in <module>
    start()
  File "/opt/spike/server/spike/start.py", line 64, in start
    app = Flask(__name__, static_folder=ui_dist_dir, static_url_path="/static", template_folder=ui_dist_dir)
  File "/opt/spike/server/envs/default/lib/python3.7/site-packages/flask/app.py", line 420, in __init__
    self.static_folder = static_folder
  File "/opt/spike/server/envs/default/lib/python3.7/site-packages/flask/helpers.py", line 1004, in static_folder
    value = value.rstrip("/\\")
AttributeError: 'PosixPath' object has no attribute 'rstrip'
```

### Environment

* Python version: 3.7.4
* Flask version: 1.1.2
* Werkzeug version: 0.16.1

**Comment by davidism** [comment]
As far as I know this was never intended to work. The change is that we now strip slashes in order to be more permissive (ironic) of the values we accept.

**Comment by mcshlain** [comment]
I wasn't sure if that was intended but I would consider supporting this in the future, and also using pathlib internally instead of dealing with path adaptations inside Flask when you already have a built in module that handles these things in python 3.

**Comment by davidism** [comment]
I'm unmarking this as a regression, since pathlib was never intentionally supported here. I think we have some fspath compat in the code for `send_file`, so if someone wants to make a PR for 1.1.x, I'd be ok with that, otherwise I'll just leave this as a general "use pathlib internally" ticket for 2.x. If you want to pass in pathlib things, just call `str` on them first in the mean time.

Honestly, I'm not sure there's much advantage to use pathlib internally, in the few places in Pallets it's been added so far it just ends up being:

```
if hasattr(thing, "__fspath__"):
    thing = os.fspath(thing)
```

which doesn't seem very convenient, just noisy. So the outcome of this ticket might be nothing if it turns out to not be useful to us internally.

**Comment by jab** [comment]
See #3579.
