### ISSUE TITLE
Clarify in the changelog that 1.1.2 is the last release to support py2.7 and py3.5

### ISSUE THREAD

**Issue by jaapz** [pallets/flask#3569]
The release notification on github says that this version is the last version to support py2.7 and py3.5, and it also says that some code has been deprecated which will be removed in 2.0. 

The changelog only mentions the couple of bugfixes, but IMHO should also mention the deprecations and the fact that this is the last version to support 2.7 and 3.5! Currently the changelog makes it seem 1.1.2 is just some patch release but in reality those are some pretty big changes that people should be made aware about, i think.

**Comment by davidism** [comment]
The deprecations are already listed in previous sections, and are also related to the other libraries used by Flask, which have their own changelogs. 1.1.x is the last version to support 2.7 and 3.5, I just wanted to reinforce that since Flask hadn't had a release since the [official announcement](https://palletsprojects.com/blog/ending-python2-support/). The 2.0 changelog does mention the dropped support.

**Comment by jaapz** [comment]
In the CHANGES.rst file in the repo it is clear, but the change log on the website isn't, because the added context of the new 2.0.0 version isn't there: https://flask.palletsprojects.com/en/1.1.x/changelog/#version-1-1-2
