### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by zxiaozhou** [pallets/flask#3584]
### Expected Behavior

```python
# Paste a minimal example that causes the problem.
```

### Actual Behavior

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Python version: 3.6
* Flask version:1.1.2
* Werkzeug version:pycharm 2020.1

**Comment by ThiefMaster** [comment]
Please stop opening issues that are lacking any information / code, or are just rants (like your previous one).

If you really think there is an issue with flask (NOT with some flask extension not developed/maintained by us), then please open a new issue that includes a minimal example to reproduce your problem.

**Comment by zxiaozhou** [comment]
@ThiefMaster Part of the network problem has not been submitted. I want to save it first and then modify it

**Comment by ThiefMaster** [comment]
Well your issue is still incomplete as it lacks any code. And it sounds like a flask-apscheduler problem anyway.

Also, please do not submit incomplete issues. This is noisy and people who check issues based on notifications will not see and re-check later (which I don't do, hence such issues being closed if they aren't complete during creation time)
