### ISSUE TITLE
flask.abort() documentation broken

### ISSUE THREAD

**Issue by Chealer** [pallets/flask#3837]
As reported in [an older ticket](https://github.com/pallets/werkzeug/issues/1683), [the documentation for abort(status, *args, **kwargs)](https://flask.palletsprojects.com/en/1.1.x/api/#flask.abort) has something wrong. It contains:

> Raises an HTTPException for the given status code or WSGI application.
> 
> If a status code is given, it will be looked up in the list of exceptions and will raise that exception. If passed a WSGI application, it will wrap it in a proxy WSGI exception and raise that:
> 
> abort(404)  # 404 Not Found
> abort(Response('Hello World'))

This is now better thanks to previous work by @cjnickel, but as he pointed out, it looks like the flask.abort() documentation is the same as werkzeug's werkzeug.exceptions.abort and it remains unclear what the author meant to write. We could start by keeping only examples about flask.abort(status, *args, **kwargs) and labelling those as such.

**Comment by greyli** [comment]
Hi, welcome to submit PRs to improve the docs you think it's unclear.

>  it looks like the flask.abort() documentation is the same as werkzeug's werkzeug.exceptions.abort

Since the `abort` function was imported directly from Werkzeug, the docs were auto generated from `werkzeug.exceptions.abort`'s docstring, that's why they are the same. In that case, if you want to update the API docs for `flask.abort`, you will need to update the docstring of [werkzeug.execptions.abort](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/exceptions.py#L852-L861).

**Comment by davidism** [comment]
I don't find the current docs unclear, and since you haven't added any information it's not clear what you expect to change. Since this is exactly what I said in the issue you opened a year ago, I'm going to close this.
