### ISSUE TITLE
PUT route requires a body to work

### ISSUE THREAD

**Issue by yellowmamba** [pallets/flask#3846]
Having a route like `@app.route("/my-put-url/<obj_id>", methods=["PUT"])`. The route only needs access to `obj_id` which is provided in the URI. There's no need for a `body` in this case. To work around it, I need to provide `{}` in the body for it to work.

### Expected Behavior
When making a PUT request __without__ a body, which I _think_ is a valid request under RFC, such request should be handled by Flask.

### Actual Behavior
Flask however returns a 400 BadRequest response. In postman, it renders like this

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

### Environment

* Python version: 3.7
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by greyli** [comment]
Flask won't require you to provide a body for PUT requests. There is something wrong with your code inside the view function. You can test this behavior simply with a minimal application:

```py
from flask import Flask

app = Flask(__name__)

@app.route('/put', methods=['PUT'])
def test_put():
    return 'Hello'
```

Since you didn't provide the view function code and the request detail, there is nothing I can help with. Besides, please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
