### ISSUE TITLE
Update documentation for easy quickstarts

### ISSUE THREAD

**Issue by sl5net** [pallets/flask#3865]
### Expected Behavior
copy past commands and run it.
tried with:
- [quickstart](https://flask.palletsprojects.com/en/1.1.x/quickstart/) 
- [flask-sqlalchemy-quickstart](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/)

### Environment
* OS version:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

* Python version:
$ python --version
Python 2.7.18

* Flask version:
$ flask --version
Python 3.8.5
Flask 1.1.2
Werkzeug 1.0.1

* Werkzeug version:
flask --version
$ flask --version
Python 3.8.5
Flask 1.1.2
Werkzeug 1.0.1
* Werkzeug version:
flask --version
...
Werkzeug 1.0.1

### Hint:
add to documentary: 
- reflect pip3 vs pip usage
- add `pip install -U Flask-SQLAlchemy` 

### explicit example problems:
https://stackoverflow.com/questions/65566823/flask-sqlalchemy-quickstart/65567007?noredirect=1#comment115927729_65567007

**Comment by greyli** [comment]
> reflect pip3 vs pip usage

If you follow the instructions of the [installation chapter](https://flask.palletsprojects.com/en/1.1.x/installation/#installation), you will get a virtual environment activated, then `pip` is the same with `pip3` if you are using Python 3 for the virtual environment.

> add pip install -U Flask-SQLAlchemy

You are right, I will try to submit a PR to add this for Flask-SQLAlchemy's quickstart. Since this is not related to this project, I'm going to close this issue. Thank you for the report.
