### ISSUE TITLE
Leading forward slashes are stripped from path variable

### ISSUE THREAD

**Issue by doctordesh** [pallets/flask#3870]
### Expected Behavior
Leading forward slashes (`/`) in path variable should be preserved when URI encoded

The value returned should be `Hello, World! - /path/to/file`.

```python
from flask import Flask
app = Flask(__name__)

@app.route('/<path:an_absolute_path>')
def hello_world(an_absolute_path):
    return "Hello, World! - %s" % an_absolute_path
```

### Actual Behavior
The value returned is `Hello, World! - path/to/file`.

```bash
> curl http://localhost:5000/%2Fpath%2Fto%2Ffile
Hello, World! - path/to/file
```

### Environment

* Python 3.6.12
* Flask 1.1.2
* Werkzeug 1.0.1

**Comment by davidism** [comment]
This is working as expected. The converter does not match a leading slash because you have to explicitly write the leading slash. Additionally, an absolute path here has little meaning, as it's relative to the URL and not to the local filesystem. You're welcome to write a custom converter that matches what you want, but I don't plan to change the built-in converter.

**Comment by doctordesh** [comment]
Thank you for your comment.

> because you have to explicitly write the leading slash.

What do you mean by this? How can I be explicit in this case?
