### ISSUE TITLE
Debug mode auto-reloader causes Uncaught Exception

### ISSUE THREAD

**Issue by sonium0** [pallets/flask#3884]
run.py:
```
from flask import Flask
app = Flask(__name__, static_url_path='')
app.config['DEBUG'] = True
# Change this line as save, to reload
app.run()
```

**Run in app.py in Visual Studio Code debugger**

### Actual Behavior

<img width="638" alt="Screenshot 2021-01-31 at 14 10 40" src="https://user-images.githubusercontent.com/5372632/106384997-3cd5f600-63ce-11eb-9343-c98202073d55.png">

### Environment

* Python version: 3.8
* Flask version: 1.1.2
* Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Make sure you create a "Flask" configuration, not just a "Run Python File" configuration. I'm sure there's a way to create a launch configuration that way too, but I don't know what it is. The exit code is how the Werkzeug reloader signals that it's reloading and not actually exiting, so that's not going to change.
