### ISSUE TITLE
feature request: secret key has a callable

### ISSUE THREAD

**Issue by dpgaspar** [pallets/flask#3950]
A request to support secret key has a callable. 

Having the possibility to dynamically change configuration values serves the following use cases:

- Easier secret rotation.
- Applications that support multiple contexts that get switched upon a request. This enables the possibility to handle secure cookie sessions from multiple distinct tenants that don't share the same encryption key.

Also it's common practice to reuse Flask secret key to encrypt other data like database fields or cache values, where other packages support callable has the encryption key.

This problem can be solved by subclassing `Flask` class. But it's a simple change, and on some cases it's not practical or clean to use a Custom Flask class.

A simple example:

``` python
import os
from flask import Flask

def secret_key_backend():
    # fetch the secret key from an external backend

app = Flask(__name__)
app.config.update(
    SECRET_KEY=secret_key_backend
)
```

**Comment by davidism** [comment]
Config is not intended to be mutable. If things change after the setup phase, behavior is undefined both in Flask and in extensions.

While itsdangerous 2.0 will have support for rotation, this PR doesn't enable that, causing all sessions to be immediately invalid every time the key rotates. In order to support upgrades across rotations, a history of keys needs to be kept, which this doesn't do.

Overall, we're not ready to support rotation, and while this is an interesting idea it requires more design before inclusion.

**Comment by dpgaspar** [comment]
@davidism,

Thank you for your reply. Right you are for key rotation, but on a multi tenant approach the secret keys change on a request basis depending on the subdomain for example, so the secure session is still valid. The idea is to make Flask mutate the secret key depending on the request. So a user with a secure session A from `A.domain.com` consistently get's the secret key A' and a user with a secure session B from `B.domain.com` consistently get's the secret key B'. 

Is this reasoning correct?

**Comment by davidism** [comment]
Flask doesn't provide any particular support for "multi tennant" configurations like you describe. It sounds like that's a better use case for subclassing and making `secret_key` a dynamic property.
