### ISSUE TITLE
AttributeError: 'module' object has no attribute 'fspath'

### ISSUE THREAD

**Issue by lzchen** [pallets/flask#4050]
`AttributeError: 'module' object has no attribute 'fspath'` exception is thrown when running `app = flask.Flask(__name__)` for flask v1.13.

Version is Python 2.7 and 3.5. I realize `fspath` is only available for Python version >= 3.6 but there shouldn't be any breaking changes from Flask 1.1.2 => 1.1.3, so the classifiers [here](https://pypi.org/project/Flask/1.1.3/) are actually incorrect.

**Comment by davidism** [comment]
Please note that Python 3.5 is no longer supported by us or Python. Also, 1.1.x, despite being the previous release, is no longer supported due to the magnitude of the 2.x release. I advise you to use a tool like [pip-compile](https://pypi.org/project/pip-tools/) to pin your dependencies, and/or begin upgrading to newer Python and Flask versions soon.

**Comment by davidism** [comment]
fixed by #4049

**Comment by davidism** [comment]
1.1.4 is available on PyPI
