### ISSUE TITLE
Exceptions are sometimes replaced with "TypeError: exceptions must derive from BaseException"

### ISSUE THREAD

**Issue by sbronson** [pallets/flask#4096]
```python
# a.py
def create_app(): raise RuntimeError()
```
```
$ FLASK_APP=a.py flask run --lazy-loading
$ curl http://127.0.0.1:5000
[...]
Traceback (most recent call last):
  File "[...]/lib/python3.9/site-packages/flask/cli.py", line 356, in __call__
    self._flush_bg_loading_exception()
  File "[...]/lib/python3.9/site-packages/flask/cli.py", line 344, in _flush_bg_loading_exception
    raise exc_info
TypeError: exceptions must derive from BaseException
```

I expected something about a RuntimeError.  `raise exc_info[1]` here worked for me https://github.com/pallets/flask/blob/7161776824734fc2797fe2b4fc974d183487ebf8/src/flask/cli.py#L342

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by richardcrichardc** [comment]
I am seeing this too. I just started a new flask project.

**Comment by cygniv404** [comment]
for me it was because i had the same function names for the same endpoint

**Comment by collinsmarra** [comment]
For me it was because of the forms, I used `flask_wtf.FlaskForm` instead of `wtforms.Form`

**Comment by thnee** [comment]
Yes thank you for reporting this, glad I am not the only one, thought I was going crazy!

This happens for **any** exception from anywhere in the project, but only sometimes, seemingly at random. It gets replaced with this `TypeError` instead of the expected stack trace / exception.

I have only observed this while running with the `flask run` dev server, not in production.

It seems to happen right after server autoreload on code update. It seems to happen on the **first** load of the page after server reload. When reloading the page again, the problem always goes away, and the expected exception / stack trace is raised.

**Comment by davidism** [comment]
I don't think the proposed fix is correct. `raise sys.exc_info()` should be valid, discarding everything but the exception instance shouldn't be required, and may be discarding rewritten tracebacks in some cases. Someone needs to identify what is invalid about `exc_info` in certain cases.

**Comment by davidism** [comment]
```python
try:
    raise RuntimeError
except RuntimeError:
    raise
```

works, but

```python
    raise sys.exc_info()
```

fails with the observed `exceptions must derive from BaseException` error. `RuntimeError` has `BaseException` in its MRO, so maybe this is a bug in Python?
