### ISSUE TITLE
CRLF in Flask's headers.set method in make_response

### ISSUE THREAD

**Issue by Captain-K-101** [pallets/flask#4238]
A crlf bug can be triggered via the headers.set method while doing a make_response this can cause
1. Header Injection
2. Relected Xss

Describe how to replicate the bug.

```
import flask
from flask import request
from flask import make_response
app = flask.Flask(__name__)


@app.route("/")
def index():
    page = request.args.get("name")
    vals = request.args.get("vals")
    r = make_response("ASDDDF")
    r.headers.set(page, vals)
    return r

app.run(host="0.0.0.0", port=8007)
```
a payload of `http://localhost:8007/?name=GET /?name=A:a%0a%0dA:d%0d%0d%0a%0dScheck&vals=dsf ` can be used to case Header Injections 

### Response
```
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 6
A:a
A:d
Scheck: dsf
Server: Werkzeug/2.0.1 Python/3.6.9
Date: Sun, 15 Aug 2021 16:06:27 GMT

ASDDDF
```

and Similarly a payload 
```http://localhost:8007/?name=%0a%0a%3Chtml%3E%3Cscript%3Ealert(%27document.location%27)%3C/script%3Easd&val=a%0aasd```
Can Cause Xss(firefox)
### Cause
The name parameter's value (name=%0a%0a<html><script>alert('not supposed to happen')</script>) is set as the header's name. But due to no sanitization, %0a can be used to inject new headers or arbitrary HTML content.

## Describe the expected behaviour that should have happened but didn't.
%0a in the header's value is sanitized and causes no CRLF(throws 500 internal error). The same could be expected in the case of header's name.

Environment:

- Python version: 3.6.9
- Flask version: 2.0.1

**Comment by ThiefMaster** [comment]
Why are you passing arbitrary user-controlled content as the header name to begin with? Is there any real-world usecase for this?

I'm quite sure we sanitize header values to prevent this - because those may indeed by set to values coming from users. But header names are usually not used in such a way...

**Comment by Captain-K-101** [comment]
The application i was creating required me to have user parsed header names with an token as value and thats when i came across this issue and since the value parameter is being sanitized i thought the name parameter should also do the same(be santized) this was the reason for creating this issue

**Comment by davidism** [comment]
Closing, this seems like you're writing an app that's deliberately insecure.

**Comment by Captain-K-101** [comment]
I am just curious, Is this more of an org based decission because it's clearly a  security issue  an similar exploit can be found here
https://github.com/golang/go/issues/47711

**Comment by davidism** [comment]
As we've both said, this appears to be you deliberately writing an insecure app. Setting headers directly with user input is a really bad idea. I can't think of a legitimate reason for an app to "require" that as you say it does.

When I saw this yesterday, it looked like you hadn't added any description in your issue, for some GitHub rendered it blank. So I didn't realize what you were trying to describe, sorry about that. 

It seems you've ignored multiple prompts by GitHub when opening an issue to "open a security issue" and "read the security guidelines." Those will tell you to responsibly report security-related issues to securit@palletsproject.com rather than in a public issue.

**Comment by Captain-K-101** [comment]
Oh Sorry About that i might have misread it and the disclosure guidelines, i'll make a report towards the correct authority via that email ,
Again Terribly sorry for the mix up
