### ISSUE TITLE
404 is returned with or without a slash.

### ISSUE THREAD

**Issue by matcha1024** [pallets/flask#4241]
Environment:

- Python version: 3.6.8  
- Flask version: 2.0.1  
- OS: Windows 10  

I used to develop with Flask 1.1.2 on Ubuntu, but when I migrated it to Flask 2.0.1 on Windows, it started returning 404s with and without slashes.  
Here is the code that results in a 404.  
  
```python
@app.route("/edit/<art_id>", methods=["GET"])
def edit_auth(art_id):
	return f"<form action='/edit/{art_id}/', method='post'> <input type='password', name='passwd'></form>"

@app.route("/edit/<art_id>", methods=["POST"])
def edit(art_id):
	global passwd
	passwd_auth = request.form["passwd"]
	if(passwd == passwd_auth):
		articles = Article.query.filter_by(id=art_id).first()
		return render_template("edit.html", articles=articles)
	else:
		return "passwd"
```
  
If I change action='/edit/{art_id}/' to action='/edit/{art_id}', it works fine.

**Comment by davidism** [comment]
This is not a bug, although I can't say why it was working previously. If a rule ends with a slash, Werkzeug's router will redirect the non-slash URL to the slash URL unless `strict_slashes=False`. If a rule does not end with a slash, only the non-slash is allowed, as you've observed.

You should use `url_for("edit", id=id)` to generate URLs instead of writing them manually. Additionally, a form that submits to the same URL doesn't need an `action`.

**Comment by matcha1024** [comment]
![スクリーンショット 2021-08-20 225745](https://user-images.githubusercontent.com/67828134/130244599-07b96452-81ae-4fa0-b7dc-8b1299ae3445.png)
![スクリーンショット 2021-08-20 225911](https://user-images.githubusercontent.com/67828134/130244791-c40798c4-a64d-4b7d-afe1-71c3858eeb07.png)
This is indeed how it works in my environment.
