### ISSUE TITLE
pass CLI arg to `create_app` when using `flask.cli.FlaskGroup` custom script

### ISSUE THREAD

**Issue by bytemain** [pallets/flask#4248]
I'm using `app factory pattern`, I create an factory function, it has one parameter: `mode`, it accepts two values: `app` or `db`.

```py
def create_app(mode):
    app = Flask(__name__)
    if mode == "app":
        init_scheduler(app)
        init_CORS(app)
```

## work in `flask_script`

previously I use `flask_script`, it has an `add_option` method, which we can set a `dest` parameter.

```python
from src import create_app
from flask_script import Manager
from flask_migrate import MigrateCommand


manager = Manager(create_app)
manager.add_option("-m", "--mode", dest="mode", default="app", required=False)
manager.add_command("db", MigrateCommand)

if __name__ == "__main__":
    manager.run(default_command="runserver")
```

and then you can use:

```bash
python manage.py runserver
python manage.py -m db migrate
```

and it will create different app instance.

**but flask-scripts can not used anymore in flask 2.0**

## some try

as the doc(<https://flask.palletsprojects.com/en/2.0.x/cli/#custom-scripts>) said:

```python
from src import create_app


import click
from click import Context

from flask.cli import FlaskGroup
from flask.cli import ScriptInfo


@click.group(cls=FlaskGroup, create_app=create_app, invoke_without_command=True)
@click.pass_context
def cli(ctx: Context):
    if ctx.invoked_subcommand is None:
        click.echo("I was invoked without subcommand")
        ctx.invoke(runserver)
    else:
        click.echo(f"I am about to invoke {ctx.invoked_subcommand}")

if name == "main":
    cli()
```

we can use `FlaskGroup`, and it has a parameter `create_app`, but I found it has no way to pass `mode` parameter to `create_app` function.

the source code says that it just create app directly: https://github.com/pallets/flask/blob/main/src/flask/cli.py#L399

so I want to see a solution for this.

**Comment by davidism** [comment]
I don't plan to add what the title specifically describes, passing an option value to a `create_app` function. Being able to add custom options that get passed to the factory instead of the command is a level of complexity I don't want to design and maintain.

Being able to pass values to a factory function for a custom CLI should probably work, since it does with the default CLI. In the default `flask` command, you can use `FLASK_APP='example:create_app(mode="app")'. I don't yet know how I want to solve this.

**Comment by reubano** [comment]
@lengthmin see my [SO answer](https://stackoverflow.com/a/61131121/408556).

**Comment by davidism** [comment]
@reubano that answer will need to be updated for Flask 2.1. `script_info` is no longer passed as the first argument to factory functions. It isn't portable once you're running outside Flask's dev server. If you want to opt in to non-portable behavior, you can use `click.get_current_context().obj` to get it, but you should ensure there is a current context first, in case you're running from Gunicorn, etc.

**Comment by davidism** [comment]
Maybe the CLI (custom or otherwise) can read a `FLASK_FACTORY_ARGS` env var that can be a string of arguments to parse and pass to the factory, just like `FLASK_APP='example:create_app(mode="app")` does.

**Comment by reubano** [comment]
More info available in #4460

**Comment by davidism** [comment]
@reubano that's not related to this issue, it's just another CLI-related issue.

**Comment by reubano** [comment]
@davidism I created that issue while trying to follow your advice about `script_info` deprecation.

**Comment by davidism** [comment]
Which is not what this issue is about...

**Comment by reubano** [comment]
@davidism this issue is about passing args to `create_app`. I currently do that (and linked to my SO answer showing how) using `script_info`.

**Comment by reubano** [comment]
@lengthmin I just created a new [SO answer](https://stackoverflow.com/a/71239560/408556) for Flask>=2.1. It works in both the dev Flask server and Gunicorn.

**Comment by davidism** [comment]
After thinking this over, I don't think anything should be done within Flask.

* There's no way to tell if a given parameter is intended for the command being executed or should be passed on to the factory.
* Adding extra parameters would require writing a custom command anyway, at which point you can do things specific to your application rather than any general solution Flask would have to come up with.
* Adding `FLASK_FACTORY_ARGS` env var doesn't make things easier, at that point you might as well set `FLASK_APP` to a callable with args, which you already can.

Click already provides a way to get the current context, and the `ScriptInfo` object on that context already has a `data` attribute to store whatever you want. So your custom group or command can take any extra parameters, process them, and add them to `ctx.obj.data`. Then the factory can check `click.get_current_context()`, and if it's available then `ctx.obj.data` will have the passed through data.
