### ISSUE TITLE
The new Mac system occupies port 5000. Can I update the flask default port

### ISSUE THREAD

**Issue by jaxonister** [pallets/flask#4328]
The new Mac system occupies port 5000. Can I update the flask default port?  mac os monterey

https://www.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/

**Comment by davidism** [comment]
`flask run -p 5001`

**Comment by greyli** [comment]
Or set the environment variable `FLASK_RUN_PORT`.

Maybe we could add a tip for this in the quickstart docs as it will become a common issue.

**Comment by ThiefMaster** [comment]
I think anyone affected by Apple's dick move of using a "nice" port - especially one widely used by various web frameworks - should use whatever channels Apple has to complain about it. I doubt it helps (especially since they might not be able to "just" change it after stuff started using it) but at least they'll realize they managed to piss off many developers.

**Comment by jaxonister** [comment]
Will the author change the default port because of this? Because when you're debugging locally, you're used to using port 5000.

**Comment by davidism** [comment]
I'm not planning to change the default yet, no. Regardless of what we do, I strongly encourage developers affected by this to provide feedback to Apple.

**Comment by davidism** [comment]
I'm also getting conflicting reports. Some people say they can't start the server. Some people say they can start it, but not connect. Some people have issues with localhost but not 127.0.0.1, or the reverse.

If we change the default only for Mac users, instructions and tutorials are now inconsistent for Mac vs other platforms. A similar difference between setting env vars for Windows already causes confusion with new users and makes instructions more complex. And if we change the default for everyone, this is one of those rare cases where that's too much change even for me; port 5000 is probably ingrained in every Flask dev's mind and every tutorial out there, there's no way to effectively deprecate it.

Right now, I'm more on the side of documenting the issue rather than changing the default.

**Comment by davidism** [comment]
Depending on when the issue actually happens when starting the app, it may be possible to catch it and show a better error with instructions. When on Mac, it could say "use a different port or disable AirPlay server". On other platforms it could probably be better anyway "another program is using this port, choose a different one or stop the other program".

**Comment by BarisX** [comment]
> I'm also getting conflicting reports. Some people say they can't start the server. Some people say they can start it, but not connect. Some people have issues with localhost but not 127.0.0.1, or the reverse.
> 
> If we change the default only for Mac users, instructions and tutorials are now inconsistent for Mac vs other platforms. A similar difference between setting env vars for Windows already causes confusion with new users and makes instructions more complex. And if we change the default for everyone, this is one of those rare cases where that's too much change even for me; port 5000 is probably ingrained in every Flask dev's mind and every tutorial out there, there's no way to effectively deprecate it.
> 
> Right now, I'm more on the side of documenting the issue rather than changing the default.

What about try to finding new ports on conflict situation?

**Comment by kkirsche** [comment]
> What about try to finding new ports on conflict situation?

Could do similar to Node's `yarn`:

```
? Something is already running on port 3000. Probably:
  /Users/username/git/docker/project/ui/node_modules/react-scripts/scripts/start.js (pid 34400)
  in /Users/username/git/docker/project/ui

Would you like to run the app on another port instead? › (Y/n)

```

**Comment by ThiefMaster** [comment]
I don't like the idea of an interactive prompt in something that's usually non-interactive... it's not so hard to suggest re-running with `-p 5001` or whatever..

**Comment by davidism** [comment]
The problem with choosing another port at runtime, automatically or with a prompt, is that it makes it really easy to start a new dev server instead of restarting an existing one. There's no way to tell that the port is being used by another application versus another instance of the dev server. So you run the server in a terminal, forget and open another terminal, run it, and now you have an old server running on 5000 and a new one on 5001. You switch to your browser, see you already had a page open, refresh it, and are confused why it doesn't reflect your new changes. I don't want to make it easy for users to make this mistake.

**Comment by davidism** [comment]
@aenglander told us he did some investigation, and it seems like it's not easy to reliably detect that the server failed with an address already in use error. It raises an `OSError`, and the exact code and message differ between operating systems and operating system versions / distros. It becomes similar to doing user agent detection to detect the different combinations, which is not particularly maintainable.

**Comment by davidism** [comment]
I've documented the error messages and how to handle them, including MacOS AirPlay info. I'll also explore detecting if the address is already in use when starting the server, but that's an issue for Werkzeug.

**Comment by BarisX** [comment]
> I don't like the idea of an interactive prompt in something that's usually non-interactive... it's not so hard to suggest re-running with `-p 5001` or whatever..

Right. True. But i prefer to push <kbd>Enter</kbd> against typing another port number.
