### ISSUE TITLE
sessions documentation (client side vs server side)

### ISSUE THREAD

**Issue by wilsaj** [pallets/flask#434]
more explicit docs on client side sessions vs server side sessions (and how to implement server-side sessions)

recent mailing list discussion: http://flask.pocoo.org/mailinglist/archive/2012/3/1/is-it-wise-for-flask-to-store-session-variables-on-the-client/
unhappy feedback: http://feedback.flask.pocoo.org/message/223

**Comment by jeffwidman** [comment]
I think the best fix is to add a sentence to the [quickstart's section on sessions](http://flask.pocoo.org/docs/dev/quickstart/#sessions) saying that if you want to handle sessions server-side rather than client-side, there are several Flask extensions that support this. I wouldn't link directly to a single extension, as extensions come and go. Mostly we just want to make folks reading this aware of the existence, and then they can google to learn more...

**Comment by dawran6** [comment]
Hi guys, could you review my commit 486ed09? Thanks!

**Comment by jeffwidman** [comment]
@dawran6 Not a big deal, but just FYI  typically you just point toward a PR, as the individual commit may change based on feedback, resulting in a different hash for the newest version. Plus, when you force-push to the PR branch that particular commit link is broken. You can link to a PR with `#34` or whatever number it is and GH will auto-link it.

**Comment by frederickOtus** [comment]
Is there a reason that this issue is still open?
