### ISSUE TITLE
Slow json loading under pypy

### ISSUE THREAD

**Issue by olliemath** [pallets/flask#4349]
For large chunks of JSON data, the following snippet (in e.g. any post request) is very slow under pypy:
```python
request.get_json()
```
in fact it's 4x slower than doing
```python
import json
json.loads(request.get_data())
```

## Expected behaviour

I would expect using the default `get_json` to be the happy path and be as fast as the in-built `json.loads`.

## Underlying cause

I tracked this down to the use of the custom `JSONDecoder` class here: https://github.com/pallets/flask/blob/main/src/flask/json/__init__.py#L53
Essentially pypy has a fast-path for the default `json.loads` - and if you use a hand-rolled decoder class you don't get to use that fast path.
Note that the `JSONDecoder` class does nothing except add some docstrings, but it's very hard for pypy to know that without some horrible introspection of the decoder class every time you call json.loads.

## Possible fix

Only set a custom `cls=` in `flask.json.load(s)` if something other than the default is set on `app.json_decoder`.

## Environment:

- Python version: pypy3.7
- Flask version: 2.0.2

**Comment by davidism** [comment]
Seems like this should be reported to PyPy.

**Comment by Base-IQ-ly-Loud** [comment]
You're a gentle(hu)MAN and a scholarly.

Sorry I was such a pill.

-------- Original Message --------
On 20 Nov 2021, 16:41, Oliver Margetts < ***@***.***> wrote:
For large chunks of JSON data, the following snippet (in e.g. any post request) is very slow under pypy:
request.get_json()
in fact it's 4x slower than doing
json.loads(request.get_data())
Expected behaviour
I would expect using the default get_json to be the happy path and be as fast as the in-built json.loads.
Underlying cause
I tracked this down to the use of the custom JSONDecoder class here: [https://github.com](<a href=)/pallets/flask/blob/main/src/flask/json/__init__.py#L53">https://github.com/pallets/flask/blob/main/src/flask/json/__init__.py#L53
Essentially pypy has a fast-path for the default json.loads - and if you use a hand-rolled decoder class you don't get to use that fast path.
Note that the JSONDecoder class does nothing except add some docstrings, but it's very hard for pypy to know that without some horrible introspection of the decoder class every time you call json.loads.
Possible fix
Only set a custom cls= in flask.json.load(s) if something other than the default is set on app.json_decoder.
Environment:
Python version: pypy3.7
Flask version: 2.0.2
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. ￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/pallets/flask/issues/4349">https://github.com/pallets/flask/issues/4349", "url": "[https://github.com](<a href=)/pallets/flask/issues/4349">https://github.com/pallets/flask/issues/4349", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by olliemath** [comment]
I reached out to them on irc - the consensus is that this is "hard to fix".
I opened the issue here, because what could be handled as an if statement
within Flask is a complex inspection of the subclass within PyPy, or a
rewrite of their JSON module.
