### ISSUE TITLE
Lazy blueprint loading feature request

### ISSUE THREAD

**Issue by azmeuk** [pallets/flask#4423]
Lately I have been profiling my unit tests, and I found that the flask application loading in my unit test fixtures is very costly. All the blueprint tree must be loaded, and all their dependencies, even if I test one single view. This brings my very capable machine to load a single unit test in several seconds. Thus, I would like to improve my project performances at import time.

[The documentation](https://flask.palletsprojects.com/en/2.0.x/patterns/lazyloading) shows a snippet for lazy view loading. I think this is very interesting, but this have some drawbacks. The main one being that this does not take advantage of the blueprints, and all the code mutualization they can bring.

I find this would be awesome if `register_blueprint` could also take strings as `blueprint` argument, so the blueprint modules would be imported at the last moment:

```python
# so we could replace this
import web.foobar
app.register_blueprint(web.foobar, url_prefix="/foobar")

# by this
app.register_blueprint("web.foobar.bp", url_prefix="/foobar")
```

I would be volunteer to tackle this if you think this is a good idea.

What do you think?

**Comment by davidism** [comment]
I should probably remove that lazy snippet, it's not really good for performance since the `cached_property` isn't likely to survive long as WSGI servers remove workers after they handle a request.

I'm not sure how you have your tests set up, but it seems like you have a different issue if creating the app takes a significant amount of time. Perhaps you need to load large resources separately. Or if you truly have so many blueprints that `register_blueprint` takes too long to add all the rules, then it might be time to create the app once for testing and reset it after each test instead of creating new apps.

I also don't see how blueprints could be lazy. Views can be lazy because you can still register it with the app and just run code to do the loading when it's accessed. But if you don't load the blueprint when it's registered, then you don't register anything that could know when it's accessed. If you do have a scheme for this, it's probably best to implement it by overriding the `Flask.register_blueprint` and `Blueprint.register` methods, I'm not confident that it would be suitable for Flask core.
