### ISSUE TITLE
BadRequest at hasattr(request, 'json')

### ISSUE THREAD

**Issue by hr-sales** [pallets/flask#4504]
Hi guys, yesterday i notice that getting or verifying 'json' in request object, an exception (BadRequest) raise

For getattr(request, 'json') or even hasattr(request, 'json') I got:

``` 
{BadRequest}400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

Someone can help me to understand? Thanks

Environment:

- Python version: 3.7, 3.9
- Flask version: Latest (2.1.0)

**Comment by davidism** [comment]
`hasattr` is actually just a `getattr` that returns `True` or `False` based on if an `AttributeError` is raised. So when you do `hasattr`, you're still executing `request.json`, which is a property that executes `request.get_json`.

In https://github.com/pallets/werkzeug/pull/2355, accessing `json` now raises a 400 error instead of returning `None` if the request is not well formed. You can use `silent=True` to make it return `None` instead, or you can use `request.is_json` instead to check if the request has a JSON content type before trying to decode the data.
