### ISSUE TITLE
flask==1.1.1 breaks with with werkzeug==2.1.0

### ISSUE THREAD

**Issue by rtindru** [pallets/flask#4505]
A recent update to the werkzeug code is breaking flask during server startup
Since `flask==1.1.1` does not pin python requirement versions, it gets installed against the latest `werkzeug==2.1.0`
In the latest `werkzeug==2.1.0`, the response classes have been refactored and the `BaseResponse` class is no longer availab.e

Install flask==1.1.1
The runserver fails with an import error due to recent changes to werkzeug
```python
Traceback (most recent call last):
  File "/usr/local/bin/moto_server", line 5, in <module>
    from moto.server import main
  File "/usr/local/lib/python3.8/dist-packages/moto/server.py", line 10, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/__init__.py)
```

Environment:
- Python version: 2.8
- Flask version: 2.1.1

**Comment by davidism** [comment]
You are using an unsupported version of the project, please update to the latest version if possible. Additionally, use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
