### ISSUE TITLE
Cannot import name 'BaseResponse' from 'werkzeug.wrappers'

### ISSUE THREAD

**Issue by lhendg1** [pallets/flask#4556]
Importing BaseResponse from werkzeug.wrappers creates an import error. 
BaseResponse has been deprecated by werkzeug in its recent release.

Flask App Server should have run. 

Environment:

- Python version: 3.9.7
- Flask version: 2.1.1

**Comment by davidism** [comment]
You are using an unsupported version of Werkzeug, please update to the latest version if possible. Use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
