### ISSUE TITLE
Flask v1.1.3 introduced many dependency conflicts

### ISSUE THREAD

**Issue by nottrobin** [pallets/flask#4589]
Flask 1.1.3 [set upper bounds](https://github.com/pallets/flask/commit/6d8b4ce9d037937ef8694067ab5754666240d097) on a bunch of dependencies that weren't there before.

This caused conflicts in many dependencies in our projects that are hard to resolve, so for now [we're just going to pin to 1.1.2](https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/pull/60).

Is this necessary? Do we have to go through and work out how to reconcile all of these dependencies? Or might it be possible to loosen up those dependencies a little?

**Comment by davidism** [comment]
Yep, we set those because so many people complained about it being incompatible, and it was before I became more strict at telling applications to pin *their* dependencies. This is a pretty good demonstration of why putting hard limits in libraries is in fact a bad idea.

Unfortunately, there's nothing to be done at this point. 1.1.x is not supported. The current supported version is 2.1.x. I suggest upgrading to that version as soon as possible. In most cases, it should be straightforward.
