### ISSUE TITLE
How do I get the name of the cli from the create_app function?

### ISSUE THREAD

**Issue by bigfoxtail** [pallets/flask#4592]
How do I get the name of the cli from the create_app function?
I have some code in create_app that I don't want to execute when I run the cli.
How to get the current cli name?
thanks
thanks
thanks

**Comment by davidism** [comment]
`click.get_current_context(silent=True)` will give you either the current Click `Context` or `None` if it was not run from the `flask` command. Note that you will never be running the code "from the CLI" when running in production, since the `flask run` development server is not appropriate for production, so consider whether "run from CLI" is the correct indicator for what you're doing.
