### ISSUE TITLE
Flask return a list directly

### ISSUE THREAD

**Issue by vba34520** [pallets/flask#4659]
```python
from flask import Flask

app = Flask(__name__)


@app.route('/')
def index():
    return [1, 2, 3]


if __name__ == '__main__':
    app.run()
```

It will raise **TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.**

Then I have to do like this.

```python
from flask import Flask, jsonify

app = Flask(__name__)


@app.route('/')
def index():
    return jsonify([1, 2, 3])


if __name__ == '__main__':
    app.run()
```

And I found that a dict can be jsonify automatically in [app.py#L1924](https://github.com/pallets/flask/blob/main/src/flask/app.py#L1924)

So why does flask can't jsonify a list like a dict ?

**Comment by davidism** [comment]
Because a sequence of values already has another meaning.

**Comment by vba34520** [comment]
How to auto jsonify a list before make_response()?

**Comment by DrizztDU** [comment]
> How to auto jsonify a list before make_response()?

`@app.route('/')` is a decorator which adds an endpoint to the `app` object. So you have two ways to do it.

1. implement a function decorator.
2. create a class `MyFlask` that inherites from class `Flask`, and override class method `route`.

**Comment by pgjones** [comment]
I would actually be better to override the `make_response` method on the `Flask` class as the route just registers the function and rule.

As David has said though, returning `["Hello", 201]` means return `"Hello"` and the status code `201`. So you'll need to somehow distinguish between this and your JSON list response.

**Comment by davidism** [comment]
So @greyli ended up implementing this in #4672. I'm a bit worried that you can return so many different things that looks somewhat similar but do different things now, but I guess everything is distinct enough still and seems to align with expectations.

- tuple is not a list, it will not be serialized to json because it provides headers and status instead
- iter[list[str | bytes]] is a streaming response, not json
- list is converted to json
