### ISSUE TITLE
Dataclasses as responses

### ISSUE THREAD

**Issue by WAKayser** [pallets/flask#4664]
In an effort improve the typing of all my API endpoints, I was looking at methods to better describe the response. I find dataclasses to be amazing for quickly describing data structures. However when returning for a route only more loosely defined types are allowed.  So I have a patch ready where dataclasses are allowed in make_response. so they can be directly returned from the view endpoint. 

So instead of for example the following:

```python
@app.route('/data/endpoint/')
def api_endpoint() -> dict:
    return {"data": 1, "message": "hello"}
```

We can more formally define the type of return data: 

```python
@dataclass
class EndpointResponse():
    data: int #: comment on the value
    message: str #: another comment to be shown in documentation
    
@app.route('/data/endpoint/')
def api_endpoint() -> EndpointResponse:
    return EndpointResponse(data=1, message="hello")
```
This would allow any documentation to directly show all fields in the json response.

**Comment by davidism** [comment]
You can override `Flask.make_response` to handle any type you want.

Or, this would be appropriate for an API extension on top of Flask. There are many actively maintained API extensions for Flask, possibly one already supports dataclasses. dataclasses are too different compared to actual response data for me to be comfortable supporting them right now in Flask itself.

The problem is that no one's going to use dataclasses like you've shown here, they're going to use references and types that aren't compatible with JSON. For example, SQLAlchemy 2.0 supports defining models from dataclasses, users will definitely want to return these and there is absolutely no way we will be able to support them. So for any reasonably complex class you end up in the same place: you need to use a serialization library to convert your Python object to valid JSON types.

**Comment by pgjones** [comment]
@WAKayser something like [Quart-Schema](https://github.com/pgjones/quart-schema)?

**Comment by pgjones** [comment]
@WAKayser I've been thinking about how to support Flask with Quart-Schema - would this be something you are interested in?
