### ISSUE TITLE
Flask does not propagate exceptions to external debugger

### ISSUE THREAD

**Issue by monim67** [pallets/flask#4729]
External debuggers like VSCode can't catch exceptions because the Werkzeug server runs with `passthrough_errors` set to `False` even though `PROPAGATE_EXCEPTIONS` config in Flask is set to `True`.

This issue has been previously reported #1674 and solved #1679, and later it was reverted #2006 to fix another issue. It seems like it was a temporary revert, but has not been revisited since.

**Comment by davidism** [comment]
There's no way to know if it's safe to pass `passthrough_errors=True` to `run_simple`, because Flask can't know that there's an external debugger running that will catch that instead. So if it's enabled in debug mode, and there's not an external debugger, then the server will just crash on any error.

Note that this only affects an external debugger's ability to catch exceptions that are not otherwise caught by Flask or Werkzeug. In my experience, this has never been a need I've had when using a debugger on a Flask application. I always set breakpoints because I have some idea of what I want to debug when I start the debugger. Additionally, passing through errors causes the server to crash, so the external debugger only works for the postmortem on that one request, which again is not as useful as tweaking something, reloading, and trying a breakpoint again.

**Comment by monim67** [comment]
The postmortem helps to investigate the bug on the spot. Otherwise you need to look for the error in console, follow the file where it broke, put a breakpoint there, and restart the server to investigate the bug. This become frustrating while developing new feature when exceptions are frequent.

> Flask can't know that there's an external debugger running that will catch that instead

Can we leverage `sys.gettrace()`, I have used to to detect debugging mode, it's None when python is not running in debug mode.

**Comment by davidism** [comment]
Yes, I understand what the benefit of a postmortem debugger is. That doesn't mean it needs to be supported by Flask. 

Can't use `gettrace` because that's used by other tools like profilers and coverage as well.

**Comment by davidism** [comment]
#954 is relevant, it describes why the original change was reverted. It is not straightforward. You're asking to re-do a lot of work to check if it's still actually an issue.

**Comment by monim67** [comment]
I got it.

I couldn't find any any workaround either, just to set `passthrough_errors` myself, may be with an environment variable, or patching anything. If anyone knows a workaround patch me through. Else the issue can be closed 👍

**Comment by miguelgrinberg** [comment]
@monim67 the workaround is to start your server with `app.run()` and set the passthrough flag in the call.
