### ISSUE TITLE
mypy 1.0 no longer accepts flask.Response as redirect type

### ISSUE THREAD

**Issue by gaborbernat** [pallets/flask#4976]
```
from __future__ import annotations

from flask import Response, redirect


def handler() -> Response:
    return redirect("")
```
```
❯ .tox/type/bin/mypy magic.py
magic.py:7: error: Incompatible return value type (got "werkzeug.wrappers.response.Response", expected "flask.wrappers.Response")  [return-value]
Found 1 error in 1 file (checked 1 source file)
~/git/dqc/bsso-flask on  timeout [!]
❯ .tox/type/bin/mypy --version
mypy 1.0.0 (compiled: yes)
```

**Comment by davidism** [comment]
Happy to consider a PR. Typing and MyPy are a mess, and it's not easy for me to keep up with.

**Comment by davidism** [comment]
I'm not sure why MyPy started failing, but this isn't something we can really fix. The issue is that `redirect` is ultimately a Werkzeug function, so it returns `werkzeug.wrappers.Response`. But you're annotating with `flask.wrappers.Response`, a subclass. You can either annotate with the Werkzeug base class, or with `flask.typing.ResponseReturnValue` or `ResponseClass`.
