### ISSUE TITLE
url_for() add support for explicit query params

### ISSUE THREAD

**Issue by michael-lazar** [pallets/flask#4979]
I have a flask route that takes the query params of the request, and uses them to build a new URL.

A simplified example looks like this:

```python

@app.route("/my-route")
def my_route():
    request_query = request.args.to_dict()
    request_query['foo'] = 'bar'    

    url = url_for("my_route", **request_query)
    return app.redirect(url)
```

So for example if you request `/my-route?value=1` you will be redirected to `/my-route?value=1&foo=bar`

Mypy started raising a type error after upgrading to Flask 2.2.

```
error: Argument 3 to "url_for" has incompatible type "**Dict[str, str]"; expected "Optional[bool]"  [arg-type]
```

I understand the source of the error: The ``**request_query`` dict could technically contain reserved keys like `"_external"` in it, which would lead to an invalid function signature. But this points to a larger bug that I had not considered, which is that unless I sanitize all of the reserved keywords (`_external`, `_method`, etc.) from my query parameters, this could lead to unexpected URLs and a possible vulnerability (e.g. somebody sending `/my-route?_scheme=http` and downgrading the redirect to http).

Even if I sanitize those reserved keywords:

- Future versions of flask could add new reserved keywords, making my code invisibly vulnerable again.
- I don't know how I would reconcile the type error without switching away from ``**request_query`` to explicit keywords, which would be very difficult in my case.

What I think would fix this, and would be a nice API to have in general, is to have an additional `_query=` keyword argument. This would  be an alternative to `**values` but would be explicitly for additional query params, with no reserved keywords.

```python
url = url_for("my_route", _query=request_query)
```

**Comment by davidism** [comment]
I don't plan to add more "_" keyword args to `url_for`, especially if their only function is to appease MyPy. The solution is to improve MyPy so that it supports valid Python patterns.

You can do `cast(dict[str, Any], query)` to make it work in your code. Your suggested fix isn't really a fix anyway, as it would fail if people are using a similar dict to pass route args instead of query args.

In this case, `request.args.to_dict` returns a `dict[str, str]`, `url_for` takes some keyword bools and `dict[str, Any]` other kwargs. I don't see a way to reconcile this with the type system as currently available through Python and MyPy. You should discuss this further with them. Or if you want to try to figure out a different annotation to use in Flask I'm willing to review a PR.

**Comment by michael-lazar** [comment]
You can ignore the type error, which is annoying but at the end of the day I don't really care about it. My main point is that the flask `url_for()` API makes it difficult/non-obvious how to write code that behaves correctly at *runtime*.

> But this points to a larger bug that I had not considered, which is that unless I sanitize all of the reserved keywords (_external, _method, etc.) from my query parameters, this could lead to unexpected URLs and a possible vulnerability (e.g. somebody sending /my-route?_scheme=http and downgrading the redirect to http).

I suspect that there are many production sites running flask right now that have this bug or some variation of it. Especially with query parameters, where unexpected values are often ignored when parsing HTTP requests.

I understand that flask is very mature and core functions like this are cemented in place. It's pretty easy to see that overloading `url_for(**values)`  to apply to both route args and query parameters was an anti-pattern in the first place, and hindsight is 20/20. But I think you should consider this as a data point if nothing else.

> Your suggested fix isn't really a fix anyway, as it would fail if people are using a similar dict to pass route args instead of query args.

No reason both can't be supported, it would actually make it easier to implement.

```python
# Instead of calling
url_for("my_route", **values)

# Allow an alternate invocation
url_for("my_route", _values=values)
```

Then at the start of `url_for` we would just need a

```python
if _values:
    values = {**_values, **values}
```

**Comment by davidism** [comment]
No, I don't plan on changing this. You're _really_ overthinking things here.

> I suspect that there are many production sites running flask right now that have this bug or some variation of it. 

I don't believe you. This isn't a useful guess to make.

> route args and query parameters was an anti-pattern

Maybe, I can't say for sure whether I would do it or not if I redesigned things. But don't act like it's an obvious answer.

> No reason

Yes, there is a reason. It means I have to implement/maintain it, figure out rules that won't satisfy some people about which form takes precedence (and how), and show people two ways to do things instead of one.
