### ISSUE TITLE
Confusing usage of `app.json_provider_class` and `app.json`

### ISSUE THREAD

**Issue by FunnySaltyFish** [pallets/flask#5190]
- Python version: 3.10.4
- Flask version: 2.3.2 

Recently I updated to Flask 2.3.2 and found that `JSONEncoder`  is removed, so I tried to find the new way to change the default json formatter. By searching the code, I found the class `DefaultJSONProvider` and wrote my own. And after I set `app.json_provider_class = CustomJsonProvider`, I found it does not work as expected. After a long time reading the source code and debugging, I realized that the `app.json` variable was not changed.

Just like what #5052 has discussed, I also think it's better to improve this API. Whether making `app.json_provider_class`  both `getter` and `setter` or making the API private might be better. I mean, not everyone will read the document of every framework, and when I want to modify the json formatter, I would like to just type `app.json` and see what the IDE will show.  Moreover, when using flask, it's rarely to see someone extends the class `Flask` to reset the `json_provider_class`, they just change the property of the global variable `app` instead.

If needed, I'm glad to PR.

**Comment by dfioravanti** [comment]
Plus a million to this. This costed me 2h of debugging because I could not understand what was going on. I think the easiest fix it to allow `json_provider_class` to be set in the constructor or the `Flask` object. I really like flask and I am really gratefully for all the effort the maintainers are putting into this. But, I am sorry to say that this is a very pointless footgun, I am absolutely open to the idea that there is a good reason to design it like this but I really cannot understand what it would be.
