### ISSUE TITLE
Flask setup.py should use "Werkzeug ~= 2.2.2" instead of "Werkzeug >= 2.2.2"

### ISSUE THREAD

**Issue by gsmethells** [pallets/flask#5285]
The recent release of Werkzeug 3.x has affected the logic of Flask setup.py causing it to install an incompatible version of Werkzeug. A change to setup.py from `>=` to `~=` would  remedy the situation until the community can verify Flask 3.x is at a known stable release point.

Actual:

`pip install Flask==2.2.2` does not create a working install of Flask

Expected:

`pip install Flask==2.2.2` should create a working install of Flask

Environment:

- Python version: 3.11
- Flask version: 2.2.2

**Comment by ThiefMaster** [comment]
You need to pin your transitive dependencies, and update them together as well. Please read one of the many issues related to this. See e.g. [this comment](https://github.com/pallets/flask/issues/5279#issuecomment-1744132550) for details.

Also, in a new project, you should use recent versions instead of older/unsupported ones.

**Comment by gsmethells** [comment]
Health care software cannot use the latest versions without going through FDA mandated verification and validation.

**Comment by ThiefMaster** [comment]
But you can use outdated and thus unsupported versions?! Anyway, in that case you should probably either:

- pin the proper (older) version of flask, werkzeug, jinja, etc
- use packages provided by your (enterprise-grade, I assume, ie RHEL) distribution instead of installing from pip

**Comment by gsmethells** [comment]
We cannot pin your dependencies because we cannot know when to move them.

**Comment by ThiefMaster** [comment]
That makes no sense...

At point X you install Flask (which pulls in werkzeug and jinja). So at that point you have a working set of dependencies. You pin those (ideally using a tool like pip-compile).

And you just said that newer versions need to be "verified and validated" (whatever that means in your context). So that's how you know when to update: As soon as you're allowed to use the newer versions...

**Comment by gsmethells** [comment]
We make new images constantly via CI. We do not install Flask once. 

We can lock Werkzeug now that we know your stance, but this creates the opposite problem when we need to move Flask up of having to figure out which other set of libraries needs to be moved. To do that, we'd have to unpin them in our pyproject.toml and re-pin them just-in-case.

We maintain our dep tree, you maintain yours or this turns into the same dependency hell of RPMs back in the late 90's.

**Comment by davidism** [comment]
When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/
