### ISSUE TITLE
running Thread object cause twice running

### ISSUE THREAD

**Issue by SigmaStar** [pallets/flask#5307]
following code cause MyThread object running twice.

```python
import threading
import time
from flask import Flask

class MyThread(threading.Thread):
    def __init__(self):
        super().__init__()
        self.event = threading.Event()

    def run(self):
        print("Hello")


app = Flask(__name__)
t1 = MyThread()
t1.start()
app.run(host='0.0.0.0', port = 19001, debug = True)
```

set debug as False can avoid this problem but why is that? Is that a feature?

**Comment by SigmaStar** [comment]
my python version is 3.9.13 and Flask version is 1.1.2

**Comment by ThiefMaster** [comment]
You're asking for support for a 3.5y old Flask version. Considering that this is an Open Source project people maintain in their free time, you are generally expected to try to reproduce a problem on the latest release first.

Anyway. this is because of the dev server's autoreloader which restarts the process (the original one monitors for changes, while the new one runs the actual app)

I'd also question why you need to run a background thread in a webapp process (and not use celery, cronjobs, etc. to offload long-running or periodic tasks) ;)
