### ISSUE TITLE
Incompatible return value type: got "werkzeug.wrappers.response.Response", expected "flask.wrappers.Response"

### ISSUE THREAD

**Issue by Azaze1l** [pallets/flask#5337]
Environment:

- Python version: 3.11
- Flask version: 3.0.0
- mypy version: 1.5.1

Hey! I recently started migrating from Flask version 2.3.2 to version 3.0.0, and I've encountered some typing bugs while doing so.

I have a simple part of a code in my project:
```python
def redirect_to_uri(uri: str) -> flask.Response:
    return flask.redirect(uri)
```
But when I migrated to version 3.0.0, mypy started to raise an error during type checking, while everything was okay on version 2.3.2:

```
main/api/helpers.py: note: In function "redirect_to_uri":
main/api/helpers.py:74:12: error: Incompatible return value type (got "werkzeug.wrappers.response.Response", expected "flask.wrappers.Response")  [return-value]
        return flask.redirect(uri)
               ^~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 29 source files)
```

I've found an old issue that could possibly help solve the described problem https://github.com/pallets/flask/issues/4600

Have a nice day:)

**Comment by davidism** [comment]
Happy to review a PR.

**Comment by kadai0308** [comment]
@davidism 
Hi I am kadai, new to here and looking forward to contribute. I think this issue is good for the beginner and i will try to fix it.

**Comment by NikhilDesai27** [comment]
Hi @Azaze1l  and @davidism,
Problem:
This is because `flask.redirect` internally calls `werkzeug.utils.redirect` which returns an instance of `werkzeug.wrappers.Response`.
See [redirect](https://github.com/pallets/flask/blob/089f6a1c50ea2b18287106ecd357522bab200510/src/flask/helpers.py#L231).

_Flask is leaking the underlying werkzeug abstractions?_

Proposed Solution:
Casting an instance of `werkzeug.wrappers.Response` to `flask.wrappers.response` before returning it and changing the annotation of `flask.redirect` appropriately.

**Comment by NikhilDesai27** [comment]
Hi @davidism,

I am happy to submit a PR subject to your approval.

**Comment by davidism** [comment]
`redirect` returns a `werkzeug.Response`, so annotating the view with `flask.Response`, a subclass, fails. Instead, use `flask.typing.ResponseClass`.

**Comment by davidism** [comment]
I'm closing this since there's nothing to fix in Flask itself, although it did make me notice that we can use that same `ResponseClass` in more places. I'll make a PR for that.
