### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by vignesh-0512** [pallets/flask#5662]
Hello  team I am planning to containerized the entire flask framework using docker so whenever user needs to work on the project they can able to run entire framework just by running docker container so can i work on this feature.

**Comment by ThiefMaster** [comment]
There's nothing that need to be done for this. You can already run a Flask app inside a container. Just use your favorite wsgi container (like uwsgi or gunicorn) in the container to run it.

**Comment by ThiefMaster** [comment]
PS: After seeing you open almost the same issue in multiple repos of various projects: Please don't do this. It's annoying for maintainers, since those issues are more noise than helpful.

Find ONE project you are actually interested in, e.g. because you use it yourself, and contribute to that. And maybe look at their open issues for things they are actually interested in.

Docker-based development workflows are probably no the lower end of interest for many projects, since especially for Python applications it's easy enough to just have a virtualenv with the dev dependencies, so there's no need at all for a docker container that's likely lacking all the tooling etc. someone may want to use.

**Comment by vignesh-0512** [comment]
ok @ThiefMaster
