### ISSUE TITLE
`redirect` calls are not caught by `handle_http_exception` while RequestRedirect is.

### ISSUE THREAD

**Issue by sergedomk** [pallets/flask#671]
I'm using Flask to implement an app that returns JSON for most requests including error responses for bad requests, page not found, etc.

To do this I wrapped the default `handle_http_exception` method of the app similar to how it was handled in the Flask_exceptional module https://github.com/jzempel/flask-exceptional/blob/master/flask_exceptional.py so that I could return the Response as JSON rather than the default generated HTML.

What I found was that any views that used the Flask `redirect` function rendered the redirect as HTML. However, if you add a route which ends with a slash, Werkzeug's routing code will automatically fire off a `RequestRedirect` which would get caught by the `handle_http_exception` and rendered as JSON.

**Comment by foxx** [comment]
Any plans to get this fixed guys?

**Comment by davidism** [comment]
Not much we can do here. You need to make your handler smarter, so it copies the headers too, if that's what you need. I'd just add a handler for `RequestRedirect` that passes it through, and add another handler for all other `HTTPExceptions` instead of trying to override `handle_http_exception`.

~~~python
@app.errorhandler(RequestRedirect)
def handle_redirect(e):
    return e

@app.errorhandler(HTTPException)
def handle_error(e):
    return 'bad', 500
~~~
